// Generated by Framer (c9b3949)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "./VMB1MMLPM.js";
const cycleOrder = ["GAg5SR5ki", "S9sCjusuZ"];
const serializationHash = "framer-Pqtku";
const variantClassNames = {
  GAg5SR5ki: "framer-v-nhntg3",
  S9sCjusuZ: "framer-v-1gqgdnx",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const SjtMRoM3M = undefined;
const mS_bNnQ2j = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Annual: "GAg5SR5ki", Monthly: "S9sCjusuZ" };
const Variants = motion.create(React.Fragment);
const getProps = ({ annual, height, id, monthly, width, ...props }) => {
  return {
    ...props,
    mS_bNnQ2j: annual ?? props.mS_bNnQ2j,
    SjtMRoM3M: monthly ?? props.SjtMRoM3M,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "GAg5SR5ki",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    mS_bNnQ2j,
    SjtMRoM3M,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "GAg5SR5ki",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1jrafiw = activeVariantCallback(async (...args) => {
    if (SjtMRoM3M) {
      const res = await SjtMRoM3M(...args);
      if (res === false) return false;
    }
  });
  const onTap8t2ti2 = activeVariantCallback(async (...args) => {
    if (mS_bNnQ2j) {
      const res = await mS_bNnQ2j(...args);
      if (res === false) return false;
    }
  });
  const onTap157xc1g = activeVariantCallback(async (...args) => {
    setVariant("GAg5SR5ki");
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-nhntg3",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Annual",
          layoutDependency: layoutDependency,
          layoutId: "GAg5SR5ki",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color":
              "var(--token-8144f193-de43-475d-87ea-e22ad062944c)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor:
              "var(--token-3482e7f4-ca60-466f-aa1f-53d45aca05d9)",
            borderBottomLeftRadius: 100,
            borderBottomRightRadius: 100,
            borderTopLeftRadius: 100,
            borderTopRightRadius: 100,
            ...style,
          },
          ...addPropertyOverrides(
            { S9sCjusuZ: { "data-framer-name": "Monthly" } },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-fmmjqk",
              "data-framer-name": "Monthly",
              "data-highlight": true,
              layoutDependency: layoutDependency,
              layoutId: "vwVrmek0p",
              onTap: onTap1jrafiw,
              style: {
                backgroundColor: "rgba(0, 0, 0, 0)",
                borderBottomLeftRadius: 100,
                borderBottomRightRadius: 100,
                borderTopLeftRadius: 100,
                borderTopRightRadius: 100,
              },
              variants: {
                S9sCjusuZ: {
                  backgroundColor:
                    "var(--token-b48b7134-7ad2-4f07-b792-c7a8003d791a, rgb(1, 43, 255))",
                },
              },
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-m10r77",
                    "data-styles-preset": "VMB1MMLPM",
                    dir: "auto",
                    children: "Monthly",
                  }),
                }),
                className: "framer-zz8cjf",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "nP_FQgIVq",
                variants: {
                  S9sCjusuZ: {
                    "--extracted-r6o4lv":
                      "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                  },
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    S9sCjusuZ: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-m10r77",
                          "data-styles-preset": "VMB1MMLPM",
                          dir: "auto",
                          style: {
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255)))",
                          },
                          children: "Monthly",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-zw80tm",
              "data-framer-name": "Annual selected",
              "data-highlight": true,
              layoutDependency: layoutDependency,
              layoutId: "ejkXg8TFn",
              onTap: onTap8t2ti2,
              style: {
                backgroundColor:
                  "var(--token-b48b7134-7ad2-4f07-b792-c7a8003d791a)",
                borderBottomLeftRadius: 100,
                borderBottomRightRadius: 100,
                borderTopLeftRadius: 100,
                borderTopRightRadius: 100,
              },
              variants: { S9sCjusuZ: { backgroundColor: "rgba(0, 0, 0, 0)" } },
              ...addPropertyOverrides(
                { S9sCjusuZ: { onTap: onTap157xc1g } },
                baseVariant,
                gestureVariant,
              ),
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-m10r77",
                      "data-styles-preset": "VMB1MMLPM",
                      dir: "auto",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b))",
                      },
                      children: "Annual",
                    }),
                  }),
                  className: "framer-1vrl7z1",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "wlpmW6_Xz",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b)",
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      S9sCjusuZ: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-m10r77",
                            "data-styles-preset": "VMB1MMLPM",
                            dir: "auto",
                            children: "Annual",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-6690np",
                  "data-framer-name": "Integrated discount",
                  layoutDependency: layoutDependency,
                  layoutId: "lC3eMAqa8",
                  style: {
                    "--border-bottom-width": "0px",
                    "--border-color": "rgba(0, 0, 0, 0)",
                    "--border-left-width": "0px",
                    "--border-right-width": "0px",
                    "--border-style": "solid",
                    "--border-top-width": "0px",
                    backgroundColor:
                      "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b)",
                    borderBottomLeftRadius: 100,
                    borderBottomRightRadius: 100,
                    borderTopLeftRadius: 100,
                    borderTopRightRadius: 100,
                  },
                  variants: {
                    S9sCjusuZ: {
                      "--border-bottom-width": "1px",
                      "--border-color":
                        "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                      "--border-left-width": "1px",
                      "--border-right-width": "1px",
                      "--border-style": "solid",
                      "--border-top-width": "1px",
                    },
                  },
                  ...addPropertyOverrides(
                    { S9sCjusuZ: { "data-border": true } },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-m10r77",
                        "data-styles-preset": "VMB1MMLPM",
                        dir: "auto",
                        children: "−20%",
                      }),
                    }),
                    className: "framer-orsaxn",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "NmUXQNrq7",
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-Pqtku.framer-1l16hsj, .framer-Pqtku .framer-1l16hsj { display: block; }",
  ".framer-Pqtku.framer-nhntg3 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; padding: 4px; position: relative; width: min-content; }",
  ".framer-Pqtku .framer-fmmjqk { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; padding: 10px 16px 10px 16px; position: relative; width: min-content; }",
  ".framer-Pqtku .framer-zz8cjf, .framer-Pqtku .framer-1vrl7z1, .framer-Pqtku .framer-orsaxn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Pqtku .framer-zw80tm { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; padding: 8px 10px 8px 16px; position: relative; width: min-content; }",
  ".framer-Pqtku .framer-6690np { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 4px 7px 4px 7px; position: relative; width: min-content; }",
  ...sharedStyle.css,
  '.framer-Pqtku[data-border="true"]::after, .framer-Pqtku [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 48
 * @framerIntrinsicWidth 208
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"S9sCjusuZ":{"layout":["auto","auto"]}}}
 * @framerVariables {"mS_bNnQ2j":"annual","SjtMRoM3M":"monthly"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerB5ge51dPW = withCSS(Component, css, "framer-Pqtku");
export default FramerB5ge51dPW;
FramerB5ge51dPW.displayName = "Toggle button";
FramerB5ge51dPW.defaultProps = { height: 48, width: 208 };
addPropertyControls(FramerB5ge51dPW, {
  variant: {
    options: ["GAg5SR5ki", "S9sCjusuZ"],
    optionTitles: ["Annual", "Monthly"],
    title: "Variant",
    type: ControlType.Enum,
  },
  mS_bNnQ2j: { title: "Annual", type: ControlType.EventHandler },
  SjtMRoM3M: { title: "Monthly", type: ControlType.EventHandler },
});
addFonts(
  FramerB5ge51dPW,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerB5ge51dPW",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "48",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"S9sCjusuZ":{"layout":["auto","auto"]}}}',
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "208",
        framerVariables: '{"mS_bNnQ2j":"annual","SjtMRoM3M":"monthly"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./B5ge51dPW.map
