// Generated by Framer (c9b3949)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-6Jr5O .framer-styles-preset-75bc7e:not(.rich-text-wrapper), .framer-6Jr5O .framer-styles-preset-75bc7e.rich-text-wrapper a { --framer-link-hover-text-color: var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, #000000); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-e8be503c-36d3-4511-8754-07379d8f8757, rgba(0, 0, 0, 0.6)); }",
];
export const className = "framer-6Jr5O";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
