// Generated by Framer (089ff9b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "./b881r4Ucu.js";
const cycleOrder = ["bmAluaDar", "d2dC0JjUS"];
const serializationHash = "framer-BUI0B";
const variantClassNames = {
  bmAluaDar: "framer-v-197rm4c",
  d2dC0JjUS: "framer-v-6sjco3",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const Xncb0wJY7 = undefined;
const XpsEjZDIF = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Active: "bmAluaDar", Inactive: "d2dC0JjUS" };
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, number, title, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "bmAluaDar",
    Xncb0wJY7: number ?? props.Xncb0wJY7 ?? "01",
    XpsEjZDIF: title ?? props.XpsEjZDIF ?? "Caption",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    Xncb0wJY7,
    XpsEjZDIF,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "bmAluaDar",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-197rm4c",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Active",
          layoutDependency: layoutDependency,
          layoutId: "bmAluaDar",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color":
              "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255))",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor:
              "var(--token-1be088de-f41b-4031-bae0-a80f52f67dfd, rgba(9, 174, 255, 0.1))",
            borderBottomLeftRadius: 8,
            borderBottomRightRadius: 8,
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            ...style,
          },
          variants: {
            d2dC0JjUS: {
              "--border-color":
                "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
              backgroundColor: "rgba(0, 0, 0, 0)",
            },
          },
          ...addPropertyOverrides(
            { d2dC0JjUS: { "data-framer-name": "Inactive" } },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-wvya7c",
              "data-framer-name": "Number container",
              layoutDependency: layoutDependency,
              layoutId: "SByX4W81g",
              style: {
                backgroundColor:
                  "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255))",
                borderBottomLeftRadius: 4,
                borderBottomRightRadius: 4,
                borderTopLeftRadius: 4,
                borderTopRightRadius: 4,
              },
              variants: {
                d2dC0JjUS: {
                  backgroundColor:
                    "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                },
              },
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.h6, {
                    className: "framer-styles-preset-1ikl6qa",
                    "data-styles-preset": "b881r4Ucu",
                    dir: "auto",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-1w1cjl5, var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255)))",
                    },
                    children: "01",
                  }),
                }),
                className: "framer-vs0zf2",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "TzuCsio5M",
                style: {
                  "--extracted-1w1cjl5":
                    "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: Xncb0wJY7,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.h6, {
                  className: "framer-styles-preset-1ikl6qa",
                  "data-styles-preset": "b881r4Ucu",
                  dir: "auto",
                  children: "Caption",
                }),
              }),
              className: "framer-ebnmiq",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "qyAYvox1d",
              style: {
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
              },
              text: XpsEjZDIF,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-BUI0B.framer-zv8pqq, .framer-BUI0B .framer-zv8pqq { display: block; }",
  ".framer-BUI0B.framer-197rm4c { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-BUI0B .framer-wvya7c { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 2px 4px 2px 4px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-BUI0B .framer-vs0zf2, .framer-BUI0B .framer-ebnmiq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ...sharedStyle.css,
  '.framer-BUI0B[data-border="true"]::after, .framer-BUI0B [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 39
 * @framerIntrinsicWidth 107.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"d2dC0JjUS":{"layout":["auto","auto"]}}}
 * @framerVariables {"Xncb0wJY7":"number","XpsEjZDIF":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerC11k882cT = withCSS(Component, css, "framer-BUI0B");
export default FramerC11k882cT;
FramerC11k882cT.displayName = "Feature indicator";
FramerC11k882cT.defaultProps = { height: 39, width: 107.5 };
addPropertyControls(FramerC11k882cT, {
  variant: {
    options: ["bmAluaDar", "d2dC0JjUS"],
    optionTitles: ["Active", "Inactive"],
    title: "Variant",
    type: ControlType.Enum,
  },
  Xncb0wJY7: {
    defaultValue: "01",
    displayTextArea: false,
    title: "Number",
    type: ControlType.String,
  },
  onXncb0wJY7Change: { changes: "Xncb0wJY7", type: ControlType.ChangeHandler },
  XpsEjZDIF: {
    defaultValue: "Caption",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onXpsEjZDIFChange: { changes: "XpsEjZDIF", type: ControlType.ChangeHandler },
});
addFonts(
  FramerC11k882cT,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerC11k882cT",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "107.5",
        framerDisplayContentsDiv: "false",
        framerVariables: '{"Xncb0wJY7":"number","XpsEjZDIF":"title"}',
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"d2dC0JjUS":{"layout":["auto","auto"]}}}',
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "39",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./C11k882cT.map
