// Generated by Framer (560da95)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  runTasksWithYield,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import FAQCard from "./eWWSXuZM8.js";
const FAQCardFonts = getFonts(FAQCard);
const cycleOrder = [
  "cg7FGWEgd",
  "KdJm5iPlT",
  "gxBNZoCcR",
  "i_V17yF6U",
  "LtmEGzhnP",
  "FQPzLvxDf",
  "uPTjwSK2T",
  "S64KlAQXQ",
];
const serializationHash = "framer-xqivN";
const variantClassNames = {
  cg7FGWEgd: "framer-v-utbeur",
  FQPzLvxDf: "framer-v-16d2owk",
  gxBNZoCcR: "framer-v-1hkhvg4",
  i_V17yF6U: "framer-v-12xoty9",
  KdJm5iPlT: "framer-v-1qlkiqz",
  LtmEGzhnP: "framer-v-fgm67r",
  S64KlAQXQ: "framer-v-12nl04n",
  uPTjwSK2T: "framer-v-1j0u5nl",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  1: "cg7FGWEgd",
  2: "KdJm5iPlT",
  3: "gxBNZoCcR",
  4: "i_V17yF6U",
  5: "LtmEGzhnP",
  6: "FQPzLvxDf",
  7: "uPTjwSK2T",
  8: "S64KlAQXQ",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "cg7FGWEgd",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "cg7FGWEgd",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const FE_m5Nxin19i1hq7 = activeVariantCallback(async (...args) => {
    setVariant("cg7FGWEgd");
  });
  const FE_m5Nxinplxwo2 = activeVariantCallback(async (...args) => {
    setVariant("KdJm5iPlT");
  });
  const FE_m5Nxing52blm = activeVariantCallback(async (...args) => {
    setVariant("gxBNZoCcR");
  });
  const FE_m5Nxinuxyrwg = activeVariantCallback(async (...args) => {
    setVariant("i_V17yF6U");
  });
  const FE_m5Nxin5upboe = activeVariantCallback(async (...args) => {
    setVariant("LtmEGzhnP");
  });
  const FE_m5Nxinymwtua = activeVariantCallback(async (...args) => {
    setVariant("FQPzLvxDf");
  });
  const FE_m5Nxin1lffg16 = activeVariantCallback(async (...args) => {
    setVariant("uPTjwSK2T");
  });
  const FE_m5Nxin1wm67n6 = activeVariantCallback(async (...args) => {
    setVariant("S64KlAQXQ");
  });
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-utbeur",
            className,
            classNames,
          ),
          "data-framer-name": "1",
          layoutDependency: layoutDependency,
          layoutId: "cg7FGWEgd",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              FQPzLvxDf: { "data-framer-name": "6" },
              gxBNZoCcR: { "data-framer-name": "3" },
              i_V17yF6U: { "data-framer-name": "4" },
              KdJm5iPlT: { "data-framer-name": "2" },
              LtmEGzhnP: { "data-framer-name": "5" },
              S64KlAQXQ: { "data-framer-name": "8" },
              uPTjwSK2T: { "data-framer-name": "7" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 0 + 0),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1qchx57-container",
                layoutDependency: layoutDependency,
                layoutId: "YgSKZSGiL-container",
                nodeId: "YgSKZSGiL",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FQf70Myxf:
                    "Most teams can begin with one focused workflow, then expand as their needs grow.",
                  height: "100%",
                  id: "YgSKZSGiL",
                  layoutId: "YgSKZSGiL",
                  maYLMI9Xd: "How quickly can we get started?",
                  style: { width: "100%" },
                  variant: matchVariant("du3IzqInE"),
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      FQPzLvxDf: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                      gxBNZoCcR: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                      i_V17yF6U: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                      KdJm5iPlT: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                      LtmEGzhnP: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                      S64KlAQXQ: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                      uPTjwSK2T: {
                        FE_m5Nxin: FE_m5Nxin19i1hq7,
                        variant: matchVariant("ACiLyXaZx"),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 76 + 16),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1wznz3p-container",
                layoutDependency: layoutDependency,
                layoutId: "p6nXnLFrE-container",
                nodeId: "p6nXnLFrE",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxinplxwo2,
                  FQf70Myxf:
                    "Fantom connects with the tools your team already uses to keep information and work in sync.",
                  height: "100%",
                  id: "p6nXnLFrE",
                  layoutId: "p6nXnLFrE",
                  maYLMI9Xd: "What tools can Intellilink connect to?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      KdJm5iPlT: {
                        FQf70Myxf:
                          "Intellilink connects with the tools your team already uses to keep information and work in sync.",
                        variant: matchVariant("du3IzqInE"),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 152 + 32),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1cyk45j-container",
                layoutDependency: layoutDependency,
                layoutId: "pyMJNbx4k-container",
                nodeId: "pyMJNbx4k",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxing52blm,
                  FQf70Myxf:
                    "Yes. Start small, validate the setup with your team, and add more workflows when ready.",
                  height: "100%",
                  id: "pyMJNbx4k",
                  layoutId: "pyMJNbx4k",
                  maYLMI9Xd: "Can we start with one workflow?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { gxBNZoCcR: { variant: matchVariant("du3IzqInE") } },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 228 + 48),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1iii3p4-container",
                layoutDependency: layoutDependency,
                layoutId: "lFyelMciy-container",
                nodeId: "lFyelMciy",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxinuxyrwg,
                  FQf70Myxf:
                    "No. Fantom works across your current stack, helping your tools operate as one connected system.",
                  height: "100%",
                  id: "lFyelMciy",
                  layoutId: "lFyelMciy",
                  maYLMI9Xd: "Does Intellilink replace our existing tools?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      i_V17yF6U: {
                        FQf70Myxf:
                          "No. Intellilink works across your current stack, helping your tools operate as one connected system.",
                        variant: matchVariant("du3IzqInE"),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 304 + 64),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-zmlg85-container",
                layoutDependency: layoutDependency,
                layoutId: "Mi0mzQR66-container",
                nodeId: "Mi0mzQR66",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxin5upboe,
                  FQf70Myxf:
                    "Yes. You decide which tools, information, and actions are available to each workflow.",
                  height: "100%",
                  id: "Mi0mzQR66",
                  layoutId: "Mi0mzQR66",
                  maYLMI9Xd: "Can we control what Intellilink can access?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { LtmEGzhnP: { variant: matchVariant("du3IzqInE") } },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 380 + 80),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-ddxvzf-container",
                layoutDependency: layoutDependency,
                layoutId: "E2MCSWS1h-container",
                nodeId: "E2MCSWS1h",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxinymwtua,
                  FQf70Myxf:
                    "Fantom uses secure access controls and keeps your information within the permissions you define.",
                  height: "100%",
                  id: "E2MCSWS1h",
                  layoutId: "E2MCSWS1h",
                  maYLMI9Xd: "How is our company data protected?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      FQPzLvxDf: {
                        FQf70Myxf:
                          "Intellilink uses secure access controls and keeps your information within the permissions you define.",
                        variant: matchVariant("du3IzqInE"),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 + 456 + 96),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-5gozuh-container",
                layoutDependency: layoutDependency,
                layoutId: "wRcWsECbc-container",
                nodeId: "wRcWsECbc",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxin1lffg16,
                  FQf70Myxf:
                    "Yes. Each workflow can match your processes, terminology, tools, and approval requirements.",
                  height: "100%",
                  id: "wRcWsECbc",
                  layoutId: "wRcWsECbc",
                  maYLMI9Xd: "Can workflows be customized for our team?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { uPTjwSK2T: { variant: matchVariant("du3IzqInE") } },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 76,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 601) - 0 - 720) / 2 +
                  532 +
                  112),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1l6n7lq-container",
                layoutDependency: layoutDependency,
                layoutId: "gznTOBqWa-container",
                nodeId: "gznTOBqWa",
                rendersWithMotion: true,
                scopeId: "dGKghXMEe",
                children: /*#__PURE__*/ _jsx(FAQCard, {
                  FE_m5Nxin: FE_m5Nxin1wm67n6,
                  FQf70Myxf:
                    "We help with setup, workflow planning, testing, and team adoption throughout the rollout.",
                  height: "100%",
                  id: "gznTOBqWa",
                  layoutId: "gznTOBqWa",
                  maYLMI9Xd: "What support is included during rollout?",
                  style: { width: "100%" },
                  variant: matchVariant("ACiLyXaZx"),
                  width: "100%",
                  ...addPropertyOverrides(
                    { S64KlAQXQ: { variant: matchVariant("du3IzqInE") } },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-xqivN.framer-1p9mmyo, .framer-xqivN .framer-1p9mmyo { display: block; }",
  ".framer-xqivN.framer-utbeur { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; max-width: 600px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 600px; }",
  ".framer-xqivN .framer-1qchx57-container, .framer-xqivN .framer-1wznz3p-container, .framer-xqivN .framer-1cyk45j-container, .framer-xqivN .framer-1iii3p4-container, .framer-xqivN .framer-zmlg85-container, .framer-xqivN .framer-ddxvzf-container, .framer-xqivN .framer-5gozuh-container, .framer-xqivN .framer-1l6n7lq-container { flex: none; height: auto; position: relative; width: 100%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 601
 * @framerIntrinsicWidth 600
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"KdJm5iPlT":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"gxBNZoCcR":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"i_V17yF6U":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"LtmEGzhnP":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"FQPzLvxDf":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"uPTjwSK2T":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"S64KlAQXQ":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerdGKghXMEe = withCSS(Component, css, "framer-xqivN");
export default FramerdGKghXMEe;
FramerdGKghXMEe.displayName = "FAQs card container";
FramerdGKghXMEe.defaultProps = { height: 601, width: 600 };
addPropertyControls(FramerdGKghXMEe, {
  variant: {
    options: [
      "cg7FGWEgd",
      "KdJm5iPlT",
      "gxBNZoCcR",
      "i_V17yF6U",
      "LtmEGzhnP",
      "FQPzLvxDf",
      "uPTjwSK2T",
      "S64KlAQXQ",
    ],
    optionTitles: ["1", "2", "3", "4", "5", "6", "7", "8"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerdGKghXMEe,
  [{ explicitInter: true, fonts: [] }, ...FAQCardFonts],
  { supportsExplicitInterCodegen: true },
);
FramerdGKghXMEe.loader = {
  load: (props, context) => {
    return runTasksWithYield(
      [() => forwardLoader(FAQCard, {}, context)],
      context,
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerdGKghXMEe",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "601",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"KdJm5iPlT":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"gxBNZoCcR":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"i_V17yF6U":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"LtmEGzhnP":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"FQPzLvxDf":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"uPTjwSK2T":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]},"S64KlAQXQ":{"layout":["fixed","auto"],"constraints":[null,"600px",null,null]}}}',
        framerColorSyntax: "true",
        framerIntrinsicWidth: "600",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./dGKghXMEe.map
