// Generated by Framer (c9b3949)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Instance,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Minus from "./vC2pior3R.js";
import Plus from "./feHWUubDx.js";
import * as sharedStyle from "./b881r4Ucu.js";
import * as sharedStyle1 from "./vapVYICQx.js";
const enabledGestures = { ACiLyXaZx: { hover: true } };
const cycleOrder = ["du3IzqInE", "ACiLyXaZx"];
const serializationHash = "framer-gcgz2";
const variantClassNames = {
  ACiLyXaZx: "framer-v-1x03gvf",
  du3IzqInE: "framer-v-1hmbhun",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const FE_m5Nxin = undefined;
const maYLMI9Xd = undefined;
const FQf70Myxf = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Collapsed: "ACiLyXaZx",
  Expanded: "du3IzqInE",
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  answers,
  click,
  height,
  id,
  question,
  width,
  ...props
}) => {
  return {
    ...props,
    FE_m5Nxin: click ?? props.FE_m5Nxin,
    FQf70Myxf: answers ?? props.FQf70Myxf ?? "Answer",
    maYLMI9Xd: question ?? props.maYLMI9Xd ?? "Question",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "du3IzqInE",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    maYLMI9Xd,
    FQf70Myxf,
    FE_m5Nxin,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "du3IzqInE",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapvnh2ge = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (FE_m5Nxin) {
      const res = await FE_m5Nxin(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "ACiLyXaZx-hover") return false;
    if (baseVariant === "ACiLyXaZx") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1hmbhun",
            className,
            classNames,
          ),
          "data-framer-name": "Expanded",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "du3IzqInE",
          onTap: onTapvnh2ge,
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 16,
            borderBottomRightRadius: 16,
            borderTopLeftRadius: 16,
            borderTopRightRadius: 16,
            ...style,
          },
          ...addPropertyOverrides(
            {
              "ACiLyXaZx-hover": { "data-framer-name": undefined },
              ACiLyXaZx: { "data-framer-name": "Collapsed" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1b1azel",
            "data-border": true,
            "data-framer-name": "Outer container",
            layoutDependency: layoutDependency,
            layoutId: "n9CINcfUs",
            style: {
              "--border-bottom-width": "1px",
              "--border-color":
                "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
              "--border-left-width": "1px",
              "--border-right-width": "1px",
              "--border-style": "solid",
              "--border-top-width": "1px",
              borderBottomLeftRadius: 16,
              borderBottomRightRadius: 16,
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
              scale: 1,
            },
            variants: { "ACiLyXaZx-hover": { scale: 0.98 } },
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-v85fft",
                "data-framer-name": "Text content",
                layoutDependency: layoutDependency,
                layoutId: "T24Dceh85",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.h6, {
                        className: "framer-styles-preset-1ikl6qa",
                        "data-styles-preset": "b881r4Ucu",
                        dir: "auto",
                        children: "Question",
                      }),
                    }),
                    className: "framer-1l6rzdn",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "b5wAl1nqN",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    text: maYLMI9Xd,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-h71b0l",
                          "data-styles-preset": "vapVYICQx",
                          dir: "auto",
                          children: "Answer",
                        }),
                      }),
                      className: "framer-7o38w",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "Lv18ssUXK",
                      style: {
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline",
                      },
                      text: FQf70Myxf,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                ],
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1pwvna7",
                "data-framer-name": "Icon container",
                layoutDependency: layoutDependency,
                layoutId: "ic8DY5pZ9",
                children: /*#__PURE__*/ _jsx(Instance, {
                  animated: true,
                  className: "framer-1pturei",
                  Component: Minus,
                  layoutDependency: layoutDependency,
                  layoutId: "KSZ6f3mVn",
                  style: {
                    "--43q7um":
                      "var(--token-e8be503c-36d3-4511-8754-07379d8f8757, rgba(0, 0, 0, 0.6))",
                  },
                  variants: {
                    "ACiLyXaZx-hover": {
                      "--43q7um":
                        "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                    },
                  },
                  ...addPropertyOverrides(
                    { ACiLyXaZx: { Component: Plus } },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-5bmy3",
                "data-framer-name": "White overlay frame",
                layoutDependency: layoutDependency,
                layoutId: "B_NDWY2J9",
                style: {
                  backgroundColor:
                    "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                  opacity: 1,
                },
                variants: { ACiLyXaZx: { opacity: 0 } },
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-gcgz2.framer-1cpoi7j, .framer-gcgz2 .framer-1cpoi7j { display: block; }",
  ".framer-gcgz2.framer-1hmbhun { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 454px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-gcgz2 .framer-1b1azel { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 16px 20px 16px 20px; position: relative; width: 1px; z-index: 1; }",
  ".framer-gcgz2 .framer-v85fft { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; z-index: 1; }",
  ".framer-gcgz2 .framer-1l6rzdn, .framer-gcgz2 .framer-7o38w { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-gcgz2 .framer-1pwvna7 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 24px; z-index: 1; }",
  ".framer-gcgz2 .framer-1pturei { aspect-ratio: 1 / 1; flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-gcgz2 .framer-5bmy3 { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; z-index: 0; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-gcgz2[data-border="true"]::after, .framer-gcgz2 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 76
 * @framerIntrinsicWidth 454
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ACiLyXaZx":{"layout":["fixed","auto"]},"JaZiBHmlB":{"layout":["fixed","auto"]}}}
 * @framerVariables {"maYLMI9Xd":"question","FQf70Myxf":"answers","FE_m5Nxin":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramereWWSXuZM8 = withCSS(Component, css, "framer-gcgz2");
export default FramereWWSXuZM8;
FramereWWSXuZM8.displayName = "FAQ card";
FramereWWSXuZM8.defaultProps = { height: 76, width: 454 };
addPropertyControls(FramereWWSXuZM8, {
  variant: {
    options: ["du3IzqInE", "ACiLyXaZx"],
    optionTitles: ["Expanded", "Collapsed"],
    title: "Variant",
    type: ControlType.Enum,
  },
  maYLMI9Xd: {
    defaultValue: "Question",
    displayTextArea: false,
    title: "Question",
    type: ControlType.String,
  },
  onmaYLMI9XdChange: { changes: "maYLMI9Xd", type: ControlType.ChangeHandler },
  FQf70Myxf: {
    defaultValue: "Answer",
    displayTextArea: false,
    title: "Answers",
    type: ControlType.String,
  },
  onFQf70MyxfChange: { changes: "FQf70Myxf", type: ControlType.ChangeHandler },
  FE_m5Nxin: { title: "Click", type: ControlType.EventHandler },
});
addFonts(
  FramereWWSXuZM8,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramereWWSXuZM8",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerVariables:
          '{"maYLMI9Xd":"question","FQf70Myxf":"answers","FE_m5Nxin":"click"}',
        framerContractVersion: "1",
        framerIntrinsicWidth: "454",
        framerIntrinsicHeight: "76",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ACiLyXaZx":{"layout":["fixed","auto"]},"JaZiBHmlB":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./eWWSXuZM8.map
