// Generated by Framer (c9b3949)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  RichText,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ChevronDown from "./BMJnfIjVN.js";
import * as sharedStyle from "./b881r4Ucu.js";
import * as sharedStyle2 from "./OsCWNv90r.js";
import * as sharedStyle1 from "./vapVYICQx.js";
const ChevronDownFonts = getFonts(ChevronDown);
const MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(motion.div),
);
const cycleOrder = ["G2LtWIzMF", "oG0O18E0V", "zu61aQF44", "qUGWbCjZF"];
const serializationHash = "framer-aU6gU";
const variantClassNames = {
  G2LtWIzMF: "framer-v-qad8t9",
  oG0O18E0V: "framer-v-1kkzsyt",
  qUGWbCjZF: "framer-v-csk4v4",
  zu61aQF44: "framer-v-1thquqv",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const N4d4wRM6n = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 2, type: "spring" };
const transition2 = { bounce: 0.2, delay: 0.5, duration: 0.4, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  1: "G2LtWIzMF",
  2: "oG0O18E0V",
  3: "zu61aQF44",
  4: "qUGWbCjZF",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ avatarVisible, height, id, width, ...props }) => {
  return {
    ...props,
    N4d4wRM6n: avatarVisible ?? props.N4d4wRM6n ?? true,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "G2LtWIzMF",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, N4d4wRM6n, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "G2LtWIzMF",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppear1mtww0w = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("zu61aQF44", true), 1500);
  });
  const onAppear1s7az0h = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("qUGWbCjZF", true), 1500);
  });
  useOnVariantChange(baseVariant, {
    oG0O18E0V: onAppear1mtww0w,
    zu61aQF44: onAppear1s7az0h,
  });
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "zu61aQF44") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-qad8t9",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "1",
          layoutDependency: layoutDependency,
          layoutId: "G2LtWIzMF",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color":
              "var(--token-a1edcf55-b80c-4b00-8dc3-d8e4199b18ee)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backdropFilter: "blur(10px)",
            backgroundColor:
              "var(--token-53d512fc-9508-4ca7-9593-aa4f8e122f95, rgba(255, 255, 255, 0.8))",
            borderBottomLeftRadius: 24,
            borderBottomRightRadius: 24,
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            WebkitBackdropFilter: "blur(10px)",
            ...style,
          },
          ...addPropertyOverrides(
            {
              oG0O18E0V: { "data-framer-name": "2", "data-highlight": true },
              qUGWbCjZF: { "data-framer-name": "4" },
              zu61aQF44: { "data-framer-name": "3", "data-highlight": true },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-nwpm6m",
              "data-framer-name": "Folder Header",
              layoutDependency: layoutDependency,
              layoutId: "n69plX9oV",
              children: [
                /*#__PURE__*/ _jsx(Image1, {
                  background: {
                    alt: "",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 24 + 0 + 34.1,
                    ),
                    pixelHeight: 90,
                    pixelWidth: 90,
                    positionX: "center",
                    positionY: "center",
                    sizes: "44px",
                    src: "https://framerusercontent.com/images/Uwu6oCqaeQirmXZy5Q37Nkh5gE.png?width=90&height=90",
                  },
                  className: "framer-1d7n2pc",
                  "data-framer-name": "Meth Lab Folder Icon",
                  layoutDependency: layoutDependency,
                  layoutId: "HBGkbYBMb",
                  style: {
                    borderBottomLeftRadius: 1e3,
                    borderBottomRightRadius: 1e3,
                    borderTopLeftRadius: 1e3,
                    borderTopRightRadius: 1e3,
                  },
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-6b0e2h",
                  "data-framer-name": "Folder Title Group",
                  layoutDependency: layoutDependency,
                  layoutId: "EXN5pqFqO",
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.h6, {
                          className: "framer-styles-preset-1ikl6qa",
                          "data-styles-preset": "b881r4Ucu",
                          dir: "auto",
                          children: "Meth Lab",
                        }),
                      }),
                      className: "framer-c9c752",
                      "data-framer-name": "Folder Name",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "ncqsZzjfc",
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-h71b0l",
                          "data-styles-preset": "vapVYICQx",
                          dir: "auto",
                          children: "159 Items",
                        }),
                      }),
                      className: "framer-9jzgn2",
                      "data-framer-name": "Folder Item Count",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "jsY4YOqhW",
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  ],
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-14n86qn",
              "data-framer-name": "Invite Controls",
              layoutDependency: layoutDependency,
              layoutId: "SeNSIg1vP",
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.h6, {
                    className: "framer-styles-preset-1ikl6qa",
                    "data-styles-preset": "b881r4Ucu",
                    dir: "auto",
                    children: "Share this folder",
                  }),
                }),
                className: "framer-p7ixss",
                "data-framer-name": "Invite Heading",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "sECXG5BWy",
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1ip8s23",
              "data-framer-name": "Access Section",
              layoutDependency: layoutDependency,
              layoutId: "Ky8USarW0",
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-3c3dzp",
                "data-framer-name": "Access List",
                layoutDependency: layoutDependency,
                layoutId: "m9yvuAFcN",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-516tb2",
                    "data-framer-name": "Jesse Pinkman Access Row",
                    layoutDependency: layoutDependency,
                    layoutId: "PgYa6DNK2",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-ida4b1",
                        "data-framer-name": "Jesse Pinkman Identity",
                        layoutDependency: layoutDependency,
                        layoutId: "jmW0h474f",
                        children: [
                          N4d4wRM6n !== false &&
                            /*#__PURE__*/ _jsx(Image1, {
                              background: {
                                alt: "",
                                fit: "fill",
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    24 +
                                    211.4 +
                                    8 +
                                    0 +
                                    0 +
                                    0 +
                                    0 +
                                    33.6,
                                ),
                                pixelHeight: 74,
                                pixelWidth: 74,
                                positionX: "center",
                                positionY: "center",
                                sizes: "40px",
                                src: "https://framerusercontent.com/images/YbIkbpKaq9pmlSfHIsww2gkTTJ4.png?width=74&height=74",
                              },
                              className: "framer-1583omd",
                              "data-framer-name": "Jesse Pinkman Avatar",
                              layoutDependency: layoutDependency,
                              layoutId: "EssSN3twx",
                              style: {
                                borderBottomLeftRadius: "100%",
                                borderBottomRightRadius: "100%",
                                borderTopLeftRadius: "100%",
                                borderTopRightRadius: "100%",
                              },
                            }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-ggr0s7",
                            "data-framer-name": "Jesse Pinkman Details",
                            layoutDependency: layoutDependency,
                            layoutId: "xys7bwxhB",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h6, {
                                    className: "framer-styles-preset-1ikl6qa",
                                    "data-styles-preset": "b881r4Ucu",
                                    dir: "auto",
                                    children: "Jesse Pinkman",
                                  }),
                                }),
                                className: "framer-hzxvol",
                                "data-framer-name": "Person Name",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "vtRMu7IIZ",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-h71b0l",
                                    "data-styles-preset": "vapVYICQx",
                                    dir: "auto",
                                    children: "bdech@gmail.com",
                                  }),
                                }),
                                className: "framer-228ton",
                                "data-framer-name": "Email Address",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "vkoXXdYGz",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1u5stj3",
                        "data-border": true,
                        "data-framer-name": "Invite Permission Select",
                        layoutDependency: layoutDependency,
                        layoutId: "ykcVWo0gY",
                        style: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          borderBottomLeftRadius: 1e3,
                          borderBottomRightRadius: 1e3,
                          borderTopLeftRadius: 1e3,
                          borderTopRightRadius: 1e3,
                        },
                        variants: {
                          zu61aQF44: {
                            "--border-color":
                              "var(--token-b48b7134-7ad2-4f07-b792-c7a8003d791a, rgb(1, 43, 255))",
                          },
                        },
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h71b0l",
                                "data-styles-preset": "vapVYICQx",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                                },
                                children: "Can view",
                              }),
                            }),
                            className: "framer-vlgmjk",
                            "data-framer-name": "Permission Label",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "HdDe7iwTX",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                qUGWbCjZF: {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      className: "framer-styles-preset-h71b0l",
                                      "data-styles-preset": "vapVYICQx",
                                      dir: "auto",
                                      style: {
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                                      },
                                      children: "Can edit",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                          /*#__PURE__*/ _jsx(ChevronDown, {
                            animated: true,
                            className: "framer-3oj4vw",
                            layoutDependency: layoutDependency,
                            layoutId: "X2DkznBd8",
                            style: {
                              "--43q7um":
                                "var(--token-3e79ca65-ed75-4cd8-98e3-44362831f65e, rgba(0, 0, 0, 0.8))",
                            },
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1y2bzq7",
                    "data-framer-name": "Gustavo Fring Access Row",
                    layoutDependency: layoutDependency,
                    layoutId: "ramQ69eFd",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-7m6ize",
                        "data-framer-name": "Gustavo Fring Identity",
                        layoutDependency: layoutDependency,
                        layoutId: "QuUR5LTnh",
                        children: [
                          N4d4wRM6n !== false &&
                            /*#__PURE__*/ _jsx(Image1, {
                              background: {
                                alt: "",
                                fit: "fill",
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    24 +
                                    211.4 +
                                    8 +
                                    0 +
                                    0 +
                                    151.2 +
                                    0 +
                                    33.6,
                                ),
                                pixelHeight: 74,
                                pixelWidth: 74,
                                positionX: "center",
                                positionY: "center",
                                sizes: "40px",
                                src: "https://framerusercontent.com/images/nKIuCad9RRDJNuMGgFOiKx2ok.png?width=74&height=74",
                              },
                              className: "framer-1uej6z5",
                              "data-framer-name": "Gustavo Fring Avatar",
                              layoutDependency: layoutDependency,
                              layoutId: "hDEhGs4t3",
                              style: {
                                borderBottomLeftRadius: "100%",
                                borderBottomRightRadius: "100%",
                                borderTopLeftRadius: "100%",
                                borderTopRightRadius: "100%",
                              },
                            }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-8olxjd",
                            "data-framer-name": "Gustavo Fring Details",
                            layoutDependency: layoutDependency,
                            layoutId: "ZrbxtzzTN",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h6, {
                                    className: "framer-styles-preset-1ikl6qa",
                                    "data-styles-preset": "b881r4Ucu",
                                    dir: "auto",
                                    children: "Gustavo Fring",
                                  }),
                                }),
                                className: "framer-1w8upvf",
                                "data-framer-name": "Person Name",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "ExuNjQqWH",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-h71b0l",
                                    "data-styles-preset": "vapVYICQx",
                                    dir: "auto",
                                    children: "thechickenman@gmail.com",
                                  }),
                                }),
                                className: "framer-1mxb85u",
                                "data-framer-name": "Email Address",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "kg0sCS_c_",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-13p1myc",
                        "data-border": true,
                        "data-framer-name": "Gustavo Fring Permission Select",
                        layoutDependency: layoutDependency,
                        layoutId: "OwYkUCpXd",
                        style: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          borderBottomLeftRadius: 1e3,
                          borderBottomRightRadius: 1e3,
                          borderTopLeftRadius: 1e3,
                          borderTopRightRadius: 1e3,
                        },
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h71b0l",
                                "data-styles-preset": "vapVYICQx",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                                },
                                children: "Can view",
                              }),
                            }),
                            className: "framer-axynci",
                            "data-framer-name": "Permission Label",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "sz40jFL51",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(ChevronDown, {
                            animated: true,
                            className: "framer-ysavei",
                            layoutDependency: layoutDependency,
                            layoutId: "PAj17VIw_",
                            style: {
                              "--43q7um":
                                "var(--token-3e79ca65-ed75-4cd8-98e3-44362831f65e, rgba(0, 0, 0, 0.8))",
                            },
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-118d2zj",
                    "data-framer-name": "Saul Goodman Access Row",
                    layoutDependency: layoutDependency,
                    layoutId: "ki9wIdbzc",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-q197qn",
                        "data-framer-name": "Saul Goodman Identity",
                        layoutDependency: layoutDependency,
                        layoutId: "Wfgycy2l8",
                        children: [
                          N4d4wRM6n !== false &&
                            /*#__PURE__*/ _jsx(Image1, {
                              background: {
                                alt: "",
                                fit: "fill",
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    24 +
                                    211.4 +
                                    8 +
                                    0 +
                                    0 +
                                    302.4 +
                                    0 +
                                    33.6,
                                ),
                                pixelHeight: 74,
                                pixelWidth: 74,
                                positionX: "center",
                                positionY: "center",
                                sizes: "40px",
                                src: "https://framerusercontent.com/images/cs3yZGn9FSQ4XwD6sY1pFBvg0k.png?width=74&height=74",
                              },
                              className: "framer-7u1sot",
                              "data-framer-name": "Saul Goodman Avatar",
                              layoutDependency: layoutDependency,
                              layoutId: "p5dS720Zo",
                              style: {
                                borderBottomLeftRadius: "100%",
                                borderBottomRightRadius: "100%",
                                borderTopLeftRadius: "100%",
                                borderTopRightRadius: "100%",
                              },
                            }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-6qqp6",
                            "data-framer-name": "Saul Goodman Details",
                            layoutDependency: layoutDependency,
                            layoutId: "Qa_Uu_vpP",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h6, {
                                    className: "framer-styles-preset-1ikl6qa",
                                    "data-styles-preset": "b881r4Ucu",
                                    dir: "auto",
                                    children: "Saul Goodman",
                                  }),
                                }),
                                className: "framer-13wcuvf",
                                "data-framer-name": "Person Name",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "ZO0DaRGWu",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-h71b0l",
                                    "data-styles-preset": "vapVYICQx",
                                    dir: "auto",
                                    children: "bettercallsaul@gmail.com",
                                  }),
                                }),
                                className: "framer-ak0mx2",
                                "data-framer-name": "Email Address",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "gLRVVmLEm",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-teuimb",
                        "data-border": true,
                        "data-framer-name": "Saul Goodman Permission Select",
                        layoutDependency: layoutDependency,
                        layoutId: "gfZDM1sdb",
                        style: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          borderBottomLeftRadius: 1e3,
                          borderBottomRightRadius: 1e3,
                          borderTopLeftRadius: 1e3,
                          borderTopRightRadius: 1e3,
                        },
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h71b0l",
                                "data-styles-preset": "vapVYICQx",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                                },
                                children: "Can view",
                              }),
                            }),
                            className: "framer-dmpmnm",
                            "data-framer-name": "Permission Label",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "dF5n5DWGg",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(ChevronDown, {
                            animated: true,
                            className: "framer-66m38s",
                            layoutDependency: layoutDependency,
                            layoutId: "V181h2FFR",
                            style: {
                              "--43q7um":
                                "var(--token-3e79ca65-ed75-4cd8-98e3-44362831f65e, rgba(0, 0, 0, 0.8))",
                            },
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1udvwjr",
                    "data-framer-name": "Mike Ehrmantraut Access Row",
                    layoutDependency: layoutDependency,
                    layoutId: "pMqQ9nanP",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-x5y6mz",
                        "data-framer-name": "Mike Ehrmantraut Identity",
                        layoutDependency: layoutDependency,
                        layoutId: "PDpEqfq0u",
                        children: [
                          N4d4wRM6n !== false &&
                            /*#__PURE__*/ _jsx(Image1, {
                              background: {
                                alt: "",
                                fit: "fill",
                                loading: getLoadingLazyAtYPosition(
                                  (componentViewport?.y || 0) +
                                    24 +
                                    211.4 +
                                    8 +
                                    0 +
                                    0 +
                                    453.6 +
                                    0 +
                                    33.6,
                                ),
                                pixelHeight: 74,
                                pixelWidth: 74,
                                positionX: "center",
                                positionY: "center",
                                sizes: "40px",
                                src: "https://framerusercontent.com/images/E6Vvalfnflvfo6p24k9l0apIXc.png?width=74&height=74",
                              },
                              className: "framer-1c86sf5",
                              "data-framer-name": "Mike Ehrmantraut Avatar",
                              layoutDependency: layoutDependency,
                              layoutId: "WWUbc24KC",
                              style: {
                                borderBottomLeftRadius: "100%",
                                borderBottomRightRadius: "100%",
                                borderTopLeftRadius: "100%",
                                borderTopRightRadius: "100%",
                              },
                            }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-exi9r1",
                            "data-framer-name": "Mike Ehrmantraut Details",
                            layoutDependency: layoutDependency,
                            layoutId: "DKGTmUE7p",
                            children: [
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.h6, {
                                    className: "framer-styles-preset-1ikl6qa",
                                    "data-styles-preset": "b881r4Ucu",
                                    dir: "auto",
                                    children: "Mike Ehrmantraut",
                                  }),
                                }),
                                className: "framer-k4tsqf",
                                "data-framer-name": "Person Name",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "iiYgZX0SQ",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-h71b0l",
                                    "data-styles-preset": "vapVYICQx",
                                    dir: "auto",
                                    children: "poppop@gmail.com",
                                  }),
                                }),
                                className: "framer-t2o1o0",
                                "data-framer-name": "Email Address",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "WM37dBTvx",
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1qk0s63",
                        "data-border": true,
                        "data-framer-name":
                          "Mike Ehrmantraut Permission Select",
                        layoutDependency: layoutDependency,
                        layoutId: "WbKesnt1u",
                        style: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          borderBottomLeftRadius: 1e3,
                          borderBottomRightRadius: 1e3,
                          borderTopLeftRadius: 1e3,
                          borderTopRightRadius: 1e3,
                        },
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-h71b0l",
                                "data-styles-preset": "vapVYICQx",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                                },
                                children: "Can view",
                              }),
                            }),
                            className: "framer-yjgs0m",
                            "data-framer-name": "Permission Label",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "c1swyxu78",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(ChevronDown, {
                            animated: true,
                            className: "framer-4uy3pa",
                            layoutDependency: layoutDependency,
                            layoutId: "a9JG5ZBpy",
                            style: {
                              "--43q7um":
                                "var(--token-3e79ca65-ed75-4cd8-98e3-44362831f65e, rgba(0, 0, 0, 0.8))",
                            },
                          }),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-hm4fz4",
              "data-framer-name": "Cursor",
              layoutDependency: layoutDependency,
              layoutId: "uuIKzHXZp",
              children: [
                /*#__PURE__*/ _jsx(SVG, {
                  className: "framer-1rzx5nd",
                  "data-framer-name": "Cursor",
                  fill: "rgba(0,0,0,1)",
                  intrinsicHeight: 26,
                  intrinsicWidth: 26,
                  layoutDependency: layoutDependency,
                  layoutId: "UVPqJWnev",
                  svg: '<svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g filter="url(#filter0_d_4_35)">\n<path d="M11.8924 23.7113L7.33378 7.71982C7.0984 6.89409 7.95602 6.18106 8.73584 6.55413L23.8385 13.7792C24.6416 14.1634 24.5812 15.3159 23.7425 15.6131L17.5312 17.8139C17.3056 17.8938 17.1164 18.0511 16.9978 18.2574L13.7318 23.9361C13.2908 24.7029 12.1347 24.5616 11.8924 23.7113Z" fill="#1570EF"/>\n<path d="M6.85075 7.8544C6.49768 6.61583 7.78362 5.54674 8.95335 6.10628L24.0564 13.3314C25.2607 13.9078 25.1699 15.6359 23.9119 16.0816L17.7012 18.2825C17.5885 18.3224 17.4939 18.4012 17.4346 18.5041L14.1679 24.1829C13.5065 25.3329 11.7731 25.1214 11.4093 23.8463L6.85075 7.8544Z" stroke="#1570EF"/>\n</g>\n<defs>\n<filter id="filter0_d_4_35" x="4.28796" y="4.45428" width="23.1241" height="23.9793" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">\n<feFlood flood-opacity="0" result="BackgroundImageFix"/>\n<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>\n<feOffset dy="1"/>\n<feGaussianBlur stdDeviation="1"/>\n<feComposite in2="hardAlpha" operator="out"/>\n<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.08 0"/>\n<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_4_35"/>\n<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_4_35" result="shape"/>\n</filter>\n</defs>\n</svg>\n',
                  withExternalLayout: true,
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-19mpez2",
                  "data-border": true,
                  "data-framer-name": "Comment",
                  layoutDependency: layoutDependency,
                  layoutId: "Jgb2dRo1n",
                  style: {
                    "--border-bottom-width": "2px",
                    "--border-color": "rgb(21, 111, 238)",
                    "--border-left-width": "2px",
                    "--border-right-width": "2px",
                    "--border-style": "solid",
                    "--border-top-width": "2px",
                    backgroundColor: "rgb(21, 111, 238)",
                    borderBottomLeftRadius: 24,
                    borderBottomRightRadius: 24,
                    borderTopLeftRadius: 24,
                    borderTopRightRadius: 24,
                  },
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-kmegkv",
                        "data-styles-preset": "OsCWNv90r",
                        dir: "auto",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255)))",
                        },
                        children: "You",
                      }),
                    }),
                    className: "framer-1jmc06p",
                    "data-framer-name": "Jake",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "xIBCV9sKc",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                      "--framer-paragraph-spacing": "16px",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                }),
              ],
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-ekv5jt",
                "data-border": true,
                "data-framer-name": "Option container",
                layoutDependency: layoutDependency,
                layoutId: "NXaoKzcjl",
                style: {
                  "--border-bottom-width": "1px",
                  "--border-color":
                    "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                  "--border-left-width": "1px",
                  "--border-right-width": "1px",
                  "--border-style": "solid",
                  "--border-top-width": "1px",
                  backgroundColor:
                    "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                  borderBottomLeftRadius: 16,
                  borderBottomRightRadius: 16,
                  borderTopLeftRadius: 16,
                  borderTopRightRadius: 16,
                },
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-h71b0l",
                        "data-styles-preset": "vapVYICQx",
                        dir: "auto",
                        children: "Can view",
                      }),
                    }),
                    className: "framer-13swl4k",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "q2USChgrg",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-h71b0l",
                        "data-styles-preset": "vapVYICQx",
                        dir: "auto",
                        children: "Can edit",
                      }),
                    }),
                    className: "framer-1l10gcb",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "SMke25xLn",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                  /*#__PURE__*/ _jsx(MotionDivWithFXWithOptimizedAppearEffect, {
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    animate: animation,
                    className: "framer-159lkib",
                    "data-framer-appear-id": "159lkib",
                    "data-framer-name": "Overlay",
                    initial: animation1,
                    layoutDependency: layoutDependency,
                    layoutId: "uYTWht93X",
                    optimized: true,
                    style: {
                      backgroundColor:
                        "var(--token-621d9ebc-4113-4c98-9cca-bbc178460970, rgba(9, 174, 255, 0.2))",
                      borderBottomLeftRadius: 8,
                      borderBottomRightRadius: 8,
                      borderTopLeftRadius: 8,
                      borderTopRightRadius: 8,
                    },
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-h71b0l",
                        "data-styles-preset": "vapVYICQx",
                        dir: "auto",
                        children: "No access",
                      }),
                    }),
                    className: "framer-17yrpp0",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "Lc5qr94HN",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                ],
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-aU6gU.framer-5mvlrx, .framer-aU6gU .framer-5mvlrx { display: block; }",
  ".framer-aU6gU.framer-qad8t9 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 24px; position: relative; width: 359px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-aU6gU .framer-nwpm6m, .framer-aU6gU .framer-516tb2, .framer-aU6gU .framer-1y2bzq7, .framer-aU6gU .framer-118d2zj, .framer-aU6gU .framer-1udvwjr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-aU6gU .framer-1d7n2pc { aspect-ratio: 1 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 44px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-aU6gU .framer-6b0e2h { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-aU6gU .framer-c9c752, .framer-aU6gU .framer-9jzgn2, .framer-aU6gU .framer-p7ixss, .framer-aU6gU .framer-hzxvol, .framer-aU6gU .framer-228ton, .framer-aU6gU .framer-1w8upvf, .framer-aU6gU .framer-1mxb85u, .framer-aU6gU .framer-13wcuvf, .framer-aU6gU .framer-ak0mx2, .framer-aU6gU .framer-k4tsqf, .framer-aU6gU .framer-t2o1o0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-aU6gU .framer-14n86qn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 0px 0px 0px; position: relative; width: 100%; }",
  ".framer-aU6gU .framer-1ip8s23 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 0px 0px 0px; position: relative; width: 100%; }",
  ".framer-aU6gU .framer-3c3dzp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-aU6gU .framer-ida4b1, .framer-aU6gU .framer-7m6ize, .framer-aU6gU .framer-q197qn, .framer-aU6gU .framer-x5y6mz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-aU6gU .framer-1583omd, .framer-aU6gU .framer-1uej6z5, .framer-aU6gU .framer-7u1sot, .framer-aU6gU .framer-1c86sf5 { aspect-ratio: 1 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 40px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-aU6gU .framer-ggr0s7, .framer-aU6gU .framer-8olxjd, .framer-aU6gU .framer-6qqp6, .framer-aU6gU .framer-exi9r1 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 3px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-aU6gU .framer-1u5stj3, .framer-aU6gU .framer-13p1myc, .framer-aU6gU .framer-teuimb, .framer-aU6gU .framer-1qk0s63 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 8px 12px 8px 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-aU6gU .framer-vlgmjk, .framer-aU6gU .framer-axynci, .framer-aU6gU .framer-dmpmnm, .framer-aU6gU .framer-yjgs0m, .framer-aU6gU .framer-1jmc06p { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-aU6gU .framer-3oj4vw, .framer-aU6gU .framer-ysavei, .framer-aU6gU .framer-66m38s, .framer-aU6gU .framer-4uy3pa { aspect-ratio: 1 / 1; flex: none; height: auto; position: relative; width: 16px; }",
  ".framer-aU6gU .framer-hm4fz4 { bottom: -100px; flex: none; height: 62px; overflow: visible; position: absolute; right: -100px; width: 90px; z-index: 1; }",
  ".framer-aU6gU .framer-1rzx5nd { flex: none; height: 26px; left: 0px; position: absolute; top: 0px; width: 26px; }",
  ".framer-aU6gU .framer-19mpez2 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; left: 22px; overflow: visible; padding: 8px 16px 8px 16px; position: absolute; top: 22px; width: min-content; }",
  ".framer-aU6gU .framer-ekv5jt { align-content: center; align-items: center; bottom: 158px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 106px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 16px; position: absolute; right: 8px; width: 138px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-aU6gU .framer-13swl4k, .framer-aU6gU .framer-1l10gcb, .framer-aU6gU .framer-17yrpp0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
  ".framer-aU6gU .framer-159lkib { flex: none; height: 32px; left: 6px; overflow: visible; position: absolute; right: 6px; top: calc(50.00000000000002% - 32px / 2); z-index: 0; }",
  ".framer-aU6gU.framer-v-1kkzsyt.framer-qad8t9, .framer-aU6gU.framer-v-1thquqv.framer-qad8t9, .framer-aU6gU.framer-v-csk4v4.framer-qad8t9 { width: 359px; }",
  ".framer-aU6gU.framer-v-1kkzsyt .framer-hm4fz4 { bottom: 219px; right: -1px; }",
  ".framer-aU6gU.framer-v-1thquqv .framer-nwpm6m, .framer-aU6gU.framer-v-1thquqv .framer-13swl4k, .framer-aU6gU.framer-v-csk4v4 .framer-nwpm6m { order: 0; }",
  ".framer-aU6gU.framer-v-1thquqv .framer-14n86qn, .framer-aU6gU.framer-v-1thquqv .framer-1l10gcb, .framer-aU6gU.framer-v-csk4v4 .framer-14n86qn { order: 1; }",
  ".framer-aU6gU.framer-v-1thquqv .framer-1ip8s23, .framer-aU6gU.framer-v-1thquqv .framer-159lkib, .framer-aU6gU.framer-v-csk4v4 .framer-1ip8s23 { order: 2; }",
  ".framer-aU6gU.framer-v-1thquqv .framer-hm4fz4 { bottom: 149px; order: 4; right: -13px; z-index: 2; }",
  ".framer-aU6gU.framer-v-1thquqv .framer-ekv5jt, .framer-aU6gU.framer-v-1thquqv .framer-17yrpp0 { order: 3; }",
  ".framer-aU6gU.framer-v-csk4v4 .framer-hm4fz4 { order: 4; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  '.framer-aU6gU[data-border="true"]::after, .framer-aU6gU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 470
 * @framerIntrinsicWidth 358.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"oG0O18E0V":{"layout":["fixed","auto"]},"zu61aQF44":{"layout":["fixed","auto"]},"qUGWbCjZF":{"layout":["fixed","auto"]}}}
 * @framerVariables {"N4d4wRM6n":"avatarVisible"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerezA3Bb8pm = withCSS(Component, css, "framer-aU6gU");
export default FramerezA3Bb8pm;
FramerezA3Bb8pm.displayName = "User roles card";
FramerezA3Bb8pm.defaultProps = { height: 470, width: 358.5 };
addPropertyControls(FramerezA3Bb8pm, {
  variant: {
    options: ["G2LtWIzMF", "oG0O18E0V", "zu61aQF44", "qUGWbCjZF"],
    optionTitles: ["1", "2", "3", "4"],
    title: "Variant",
    type: ControlType.Enum,
  },
  N4d4wRM6n: {
    defaultValue: true,
    title: "Avatar visible",
    type: ControlType.Boolean,
  },
  onN4d4wRM6nChange: { changes: "N4d4wRM6n", type: ControlType.ChangeHandler },
});
addFonts(
  FramerezA3Bb8pm,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ChevronDownFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerezA3Bb8pm",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"oG0O18E0V":{"layout":["fixed","auto"]},"zu61aQF44":{"layout":["fixed","auto"]},"qUGWbCjZF":{"layout":["fixed","auto"]}}}',
        framerVariables: '{"N4d4wRM6n":"avatarVisible"}',
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerIntrinsicHeight: "470",
        framerIntrinsicWidth: "358.5",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./ezA3Bb8pm.map
