// Generated by Framer (c9b3949)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Instance,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ArrowRight from "./gXjG4ReaI.js";
import * as sharedStyle from "./WbW1RfUZV.js";
const enabledGestures = {
  AfZO288ir: { hover: true },
  jlYR3ckV6: { hover: true },
  L4yW9kxuA: { hover: true },
  n1gMtcmI9: { hover: true },
  YnCyd7g0P: { hover: true },
};
const cycleOrder = [
  "n1gMtcmI9",
  "jlYR3ckV6",
  "AfZO288ir",
  "YnCyd7g0P",
  "L4yW9kxuA",
];
const serializationHash = "framer-lpYOQ";
const variantClassNames = {
  AfZO288ir: "framer-v-1rwmjhz",
  jlYR3ckV6: "framer-v-17717ly",
  L4yW9kxuA: "framer-v-5biykp",
  n1gMtcmI9: "framer-v-17mteho",
  YnCyd7g0P: "framer-v-1gshk6h",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const F05bztbU6 = undefined;
const oGE0W8Khx = undefined;
const VOL5lEKBp = undefined;
const yy2KWrRCF = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Desktop/primary light": "AfZO288ir",
  "Desktop/primary": "n1gMtcmI9",
  "Desktop/primary/small": "YnCyd7g0P",
  "Desktop/Secondary": "jlYR3ckV6",
  "Desktop/secondary/small": "L4yW9kxuA",
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  height,
  icon,
  iconVisible,
  id,
  label,
  link,
  width,
  ...props
}) => {
  return {
    ...props,
    F05bztbU6: link ?? props.F05bztbU6,
    oGE0W8Khx: label ?? props.oGE0W8Khx ?? "Button",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "n1gMtcmI9",
    VOL5lEKBp: iconVisible ?? props.VOL5lEKBp ?? true,
    yy2KWrRCF: icon ?? props.yy2KWrRCF ?? ArrowRight,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    oGE0W8Khx,
    yy2KWrRCF,
    VOL5lEKBp,
    F05bztbU6,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "n1gMtcmI9",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: F05bztbU6,
          motionChild: true,
          nodeId: "n1gMtcmI9",
          openInNewTab: false,
          scopeId: "Jh9jZPCX6",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(scopingClassNames, "framer-17mteho", className, classNames)} framer-ndv326`,
            "data-framer-name": "Desktop/primary",
            layoutDependency: layoutDependency,
            layoutId: "n1gMtcmI9",
            ref: refBinding,
            style: {
              "--border-bottom-width": "0px",
              "--border-color": "rgba(0, 0, 0, 0)",
              "--border-left-width": "0px",
              "--border-right-width": "0px",
              "--border-style": "solid",
              "--border-top-width": "0px",
              backgroundColor:
                "var(--token-b48b7134-7ad2-4f07-b792-c7a8003d791a, rgb(1, 43, 255))",
              borderBottomLeftRadius: 1e3,
              borderBottomRightRadius: 1e3,
              borderTopLeftRadius: 1e3,
              borderTopRightRadius: 1e3,
              ...style,
            },
            variants: {
              "AfZO288ir-hover": {
                backgroundColor:
                  "var(--token-fd2642e7-ea40-4298-8994-88ab422747df, rgb(99, 213, 255))",
              },
              "n1gMtcmI9-hover": {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
                backgroundColor:
                  "var(--token-52fd1831-77d8-4d28-b23b-c4a80f84cb84, rgb(2, 37, 212))",
              },
              "YnCyd7g0P-hover": {
                backgroundColor:
                  "var(--token-52fd1831-77d8-4d28-b23b-c4a80f84cb84, rgb(2, 37, 212))",
              },
              AfZO288ir: {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
                backgroundColor:
                  "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(99, 213, 255))",
              },
              jlYR3ckV6: {
                "--border-bottom-width": "1px",
                "--border-color":
                  "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                "--border-left-width": "1px",
                "--border-right-width": "1px",
                "--border-style": "solid",
                "--border-top-width": "1px",
                backgroundColor: "rgba(0, 0, 0, 0)",
              },
              L4yW9kxuA: {
                "--border-bottom-width": "1px",
                "--border-color":
                  "var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2))",
                "--border-left-width": "1px",
                "--border-right-width": "1px",
                "--border-style": "solid",
                "--border-top-width": "1px",
                backgroundColor: "rgba(0, 0, 0, 0)",
              },
              YnCyd7g0P: {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
              },
            },
            ...addPropertyOverrides(
              {
                "AfZO288ir-hover": { "data-framer-name": undefined },
                "jlYR3ckV6-hover": { "data-framer-name": undefined },
                "L4yW9kxuA-hover": { "data-framer-name": undefined },
                "n1gMtcmI9-hover": { "data-framer-name": undefined },
                "YnCyd7g0P-hover": { "data-framer-name": undefined },
                AfZO288ir: { "data-framer-name": "Desktop/primary light" },
                jlYR3ckV6: {
                  "data-border": true,
                  "data-framer-name": "Desktop/Secondary",
                },
                L4yW9kxuA: {
                  "data-border": true,
                  "data-framer-name": "Desktop/secondary/small",
                },
                YnCyd7g0P: { "data-framer-name": "Desktop/primary/small" },
              },
              baseVariant,
              gestureVariant,
            ),
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1v2ennk",
                    "data-styles-preset": "WbW1RfUZV",
                    dir: "auto",
                    children: "Button",
                  }),
                }),
                className: "framer-1lrieaf",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "SOtHEFqPy",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: oGE0W8Khx,
                variants: {
                  jlYR3ckV6: {
                    "--extracted-r6o4lv":
                      "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                  },
                  L4yW9kxuA: {
                    "--extracted-r6o4lv":
                      "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                  },
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    jlYR3ckV6: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-1v2ennk",
                          "data-styles-preset": "WbW1RfUZV",
                          dir: "auto",
                          style: {
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                          },
                          children: "Button",
                        }),
                      }),
                    },
                    L4yW9kxuA: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-1v2ennk",
                          "data-styles-preset": "WbW1RfUZV",
                          dir: "auto",
                          style: {
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)))",
                          },
                          children: "Button",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
              VOL5lEKBp !== false &&
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-22cvhj",
                  "data-framer-name": "Icon container",
                  layoutDependency: layoutDependency,
                  layoutId: "ZoTrgAnfY",
                  children: /*#__PURE__*/ _jsx(Instance, {
                    animated: true,
                    className: "framer-x212nc",
                    Component: yy2KWrRCF,
                    layoutDependency: layoutDependency,
                    layoutId: "Tu_RabtGf",
                    style: {
                      "--1m973uw":
                        "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                      "--js9iwy": 2,
                    },
                    variants: {
                      jlYR3ckV6: {
                        "--1m973uw":
                          "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                      },
                      L4yW9kxuA: {
                        "--1m973uw":
                          "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                      },
                    },
                  }),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-lpYOQ.framer-ndv326, .framer-lpYOQ .framer-ndv326 { display: block; }",
  ".framer-lpYOQ.framer-17mteho { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 10px 16px 10px 16px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-lpYOQ .framer-1lrieaf { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-lpYOQ .framer-22cvhj { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 16px; }",
  ".framer-lpYOQ .framer-x212nc { aspect-ratio: 1 / 1; flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-lpYOQ.framer-v-1gshk6h.framer-17mteho, .framer-lpYOQ.framer-v-5biykp.framer-17mteho { padding: 6px 12px 6px 12px; }",
  ...sharedStyle.css,
  '.framer-lpYOQ[data-border="true"]::after, .framer-lpYOQ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 45.5
 * @framerIntrinsicWidth 106
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"jlYR3ckV6":{"layout":["auto","auto"]},"AfZO288ir":{"layout":["auto","auto"]},"YnCyd7g0P":{"layout":["auto","auto"]},"L4yW9kxuA":{"layout":["auto","auto"]},"kQ_lUVPEW":{"layout":["auto","auto"]},"SczAaQpxI":{"layout":["auto","auto"]},"PjI16V_UY":{"layout":["auto","auto"]},"mpY6VunvD":{"layout":["auto","auto"]},"ZOkDI5i7z":{"layout":["auto","auto"]}}}
 * @framerVariables {"oGE0W8Khx":"label","yy2KWrRCF":"icon","VOL5lEKBp":"iconVisible","F05bztbU6":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["Y7SpbVH16cWqMhj75z1M"]
 */ const FramerJh9jZPCX6 = withCSS(Component, css, "framer-lpYOQ");
export default FramerJh9jZPCX6;
FramerJh9jZPCX6.displayName = "Button";
FramerJh9jZPCX6.defaultProps = { height: 45.5, width: 106 };
addPropertyControls(FramerJh9jZPCX6, {
  variant: {
    options: ["n1gMtcmI9", "jlYR3ckV6", "AfZO288ir", "YnCyd7g0P", "L4yW9kxuA"],
    optionTitles: [
      "Desktop/primary",
      "Desktop/Secondary",
      "Desktop/primary light",
      "Desktop/primary/small",
      "Desktop/secondary/small",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  oGE0W8Khx: {
    defaultValue: "Button",
    displayTextArea: false,
    title: "Label",
    type: ControlType.String,
  },
  onoGE0W8KhxChange: { changes: "oGE0W8Khx", type: ControlType.ChangeHandler },
  yy2KWrRCF: {
    defaultValue: {
      identifier:
        "module:4G0pHPXdxDC0q34eFfFr/oq0PkaqnOfre09AZeL9M/gXjG4ReaI.js:default",
      moduleId: "4G0pHPXdxDC0q34eFfFr",
    },
    setModuleId: "Y7SpbVH16cWqMhj75z1M",
    title: "Icon",
    type: ControlType.VectorSetItem,
  },
  VOL5lEKBp: {
    defaultValue: true,
    title: "Icon visible",
    type: ControlType.Boolean,
  },
  onVOL5lEKBpChange: { changes: "VOL5lEKBp", type: ControlType.ChangeHandler },
  F05bztbU6: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerJh9jZPCX6,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerJh9jZPCX6",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"jlYR3ckV6":{"layout":["auto","auto"]},"AfZO288ir":{"layout":["auto","auto"]},"YnCyd7g0P":{"layout":["auto","auto"]},"L4yW9kxuA":{"layout":["auto","auto"]},"kQ_lUVPEW":{"layout":["auto","auto"]},"SczAaQpxI":{"layout":["auto","auto"]},"PjI16V_UY":{"layout":["auto","auto"]},"mpY6VunvD":{"layout":["auto","auto"]},"ZOkDI5i7z":{"layout":["auto","auto"]}}}',
        framerVariables:
          '{"oGE0W8Khx":"label","yy2KWrRCF":"icon","VOL5lEKBp":"iconVisible","F05bztbU6":"link"}',
        framerComponentViewportWidth: "true",
        framerVectorSets: '["Y7SpbVH16cWqMhj75z1M"]',
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "45.5",
        framerIntrinsicWidth: "106",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Jh9jZPCX6.map
