// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask =
  'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 10 C 0 4.477 4.477 0 10 0 C 15.523 0 20 4.477 20 10 C 20 15.523 15.523 20 10 20 C 4.477 20 0 15.523 0 10 Z" fill="transparent" height="20px" id="znhO0caZM" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(2 2)" width="20px"/><path d="M 8.48 0 L 6.36 6.36 L 0 8.48 L 2.12 2.12 Z" fill="transparent" height="8.479999999999999px" id="GvUrFodp8" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(7.76 7.76)" width="8.479999999999999px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ height, id, stroke, width, ...props }) => {
  return { ...props, UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)" };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
    getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-WPlfr", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--43q7um": UO5clYVeQ, ...style },
  });
});
const css = [
  `.framer-WPlfr { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"UO5clYVeQ":"stroke"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Compass","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-WPlfr");
Icon.displayName = "Compass";
export default Icon;
addPropertyControls(Icon, {
  UO5clYVeQ: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Stroke",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerDisableUnlink: "true",
        framerVariables: '{"UO5clYVeQ":"stroke"}',
        framerContractVersion: "1",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "24",
        framerVector:
          '{"name":"Compass","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}',
        framerIntrinsicHeight: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
