// Generated by Framer (089ff9b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Instance,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Feather from "./mAKyPWQFl.js";
import * as sharedStyle from "./vapVYICQx.js";
const cycleOrder = ["BYnhqdO_k", "c_qE4utIC"];
const serializationHash = "framer-aCb8T";
const variantClassNames = {
  BYnhqdO_k: "framer-v-jj6crs",
  c_qE4utIC: "framer-v-o5m6rn",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const T23Labgnv = undefined;
const Y6PDMjjDn = undefined;
const yCbtA9Hxn = undefined;
const X2sPxkebi = undefined;
const transition1 = { bounce: 0.2, delay: 0.3, duration: 1, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Active: "c_qE4utIC", Inactive: "BYnhqdO_k" };
const Variants = motion.create(React.Fragment);
const getProps = ({
  border,
  height,
  icon,
  iconText,
  id,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    T23Labgnv: border ??
      props.T23Labgnv ?? {
        borderColor:
          'var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2)) /* {"name":"Dark 20%"} */',
        borderStyle: "solid",
        borderWidth: 1,
      },
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "BYnhqdO_k",
    X2sPxkebi: title ?? props.X2sPxkebi ?? "How it works",
    Y6PDMjjDn:
      iconText ??
      props.Y6PDMjjDn ??
      "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
    yCbtA9Hxn: icon ?? props.yCbtA9Hxn ?? Feather,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    X2sPxkebi,
    yCbtA9Hxn,
    Y6PDMjjDn,
    T23Labgnv,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "BYnhqdO_k",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "c_qE4utIC") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-jj6crs",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Inactive",
          layoutDependency: layoutDependency,
          layoutId: "BYnhqdO_k",
          ref: refBinding,
          style: {
            "--border-bottom-width":
              (T23Labgnv?.borderBottomWidth ?? T23Labgnv?.borderWidth) + "px",
            "--border-color": T23Labgnv?.borderColor,
            "--border-left-width":
              (T23Labgnv?.borderLeftWidth ?? T23Labgnv?.borderWidth) + "px",
            "--border-right-width":
              (T23Labgnv?.borderRightWidth ?? T23Labgnv?.borderWidth) + "px",
            "--border-style": T23Labgnv?.borderStyle,
            "--border-top-width":
              (T23Labgnv?.borderTopWidth ?? T23Labgnv?.borderWidth) + "px",
            borderBottomLeftRadius: 1e3,
            borderBottomRightRadius: 1e3,
            borderTopLeftRadius: 1e3,
            borderTopRightRadius: 1e3,
            ...style,
          },
          ...addPropertyOverrides(
            { c_qE4utIC: { "data-framer-name": "Active" } },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(Instance, {
              animated: true,
              className: "framer-ckhna9",
              Component: yCbtA9Hxn,
              layoutDependency: layoutDependency,
              layoutId: "OB7y22byz",
              style: { "--43q7um": Y6PDMjjDn },
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-h71b0l",
                    "data-styles-preset": "vapVYICQx",
                    dir: "auto",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--variable-reference-Y6PDMjjDn-PR2FImO_h))",
                    },
                    children: "How it works",
                  }),
                }),
                className: "framer-1edq02m",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "XAgKXN1PW",
                style: {
                  "--extracted-r6o4lv":
                    "var(--variable-reference-Y6PDMjjDn-PR2FImO_h)",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                  "--variable-reference-Y6PDMjjDn-PR2FImO_h": Y6PDMjjDn,
                },
                text: X2sPxkebi,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-aCb8T.framer-o6yp1e, .framer-aCb8T .framer-o6yp1e { display: block; }",
  ".framer-aCb8T.framer-jj6crs { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-aCb8T .framer-ckhna9 { aspect-ratio: 1 / 1; flex: none; height: auto; position: relative; width: 16px; }",
  ".framer-aCb8T .framer-1edq02m { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-aCb8T.framer-v-o5m6rn.framer-jj6crs { padding: 6px 12px 6px 12px; }",
  ...sharedStyle.css,
  '.framer-aCb8T[data-border="true"]::after, .framer-aCb8T [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"c_qE4utIC":{"layout":["auto","auto"]}}}
 * @framerVariables {"X2sPxkebi":"title","yCbtA9Hxn":"icon","Y6PDMjjDn":"iconText","T23Labgnv":"border"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["fiHEoJwBMFnT6QLOcpPz"]
 */ const FramerPR2FImO_h = withCSS(Component, css, "framer-aCb8T");
export default FramerPR2FImO_h;
FramerPR2FImO_h.displayName = "Tag";
FramerPR2FImO_h.defaultProps = { height: 32, width: 32 };
addPropertyControls(FramerPR2FImO_h, {
  variant: {
    options: ["BYnhqdO_k", "c_qE4utIC"],
    optionTitles: ["Inactive", "Active"],
    title: "Variant",
    type: ControlType.Enum,
  },
  X2sPxkebi: {
    defaultValue: "How it works",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onX2sPxkebiChange: { changes: "X2sPxkebi", type: ControlType.ChangeHandler },
  yCbtA9Hxn: {
    defaultValue: {
      identifier:
        "module:407RSC1iN7xY9tZK0Q8x/uOxystmK67s4TBrM8cle/mAKyPWQFl.js:default",
      moduleId: "407RSC1iN7xY9tZK0Q8x",
    },
    setModuleId: "fiHEoJwBMFnT6QLOcpPz",
    title: "Icon",
    type: ControlType.VectorSetItem,
  },
  Y6PDMjjDn: {
    defaultValue:
      'var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0)) /* {"name":"Dark"} */',
    title: "Icon & text",
    type: ControlType.Color,
  },
  T23Labgnv: {
    defaultValue: {
      borderColor:
        'var(--token-e27a17f3-e906-4d22-a82d-877fde504653, rgba(0, 0, 0, 0.2)) /* {"name":"Dark 20%"} */',
      borderStyle: "solid",
      borderWidth: 1,
    },
    title: "Border",
    type: ControlType.Border,
  },
});
addFonts(
  FramerPR2FImO_h,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerPR2FImO_h",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerIntrinsicWidth: "32",
        framerIntrinsicHeight: "32",
        framerVectorSets: '["fiHEoJwBMFnT6QLOcpPz"]',
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"X2sPxkebi":"title","yCbtA9Hxn":"icon","Y6PDMjjDn":"iconText","T23Labgnv":"border"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"c_qE4utIC":{"layout":["auto","auto"]}}}',
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./PR2FImO_h.map
