// Generated by Framer (65a4904)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "./ffQArjjfb.js";
import * as sharedStyle1 from "./OsCWNv90r.js";
const serializationHash = "framer-awli9";
const variantClassNames = { c67AavYPv: "framer-v-1ax6vdg" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const l8krc8cgY = undefined;
const OU5zgLyJt = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, number, title, width, ...props }) => {
  return {
    ...props,
    l8krc8cgY: number ?? props.l8krc8cgY ?? "3.2\xd7",
    OU5zgLyJt: title ?? props.OU5zgLyJt ?? "workflow throughput",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    l8krc8cgY,
    OU5zgLyJt,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "c67AavYPv",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1ax6vdg",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "c67AavYPv",
          ref: refBinding,
          style: {
            "--border-bottom-width": "0px",
            "--border-color":
              "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255))",
            "--border-left-width": "2px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "0px",
            ...style,
          },
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.h3, {
                  className: "framer-styles-preset-dd75g8",
                  "data-styles-preset": "ffQArjjfb",
                  dir: "auto",
                  style: { "--framer-text-alignment": "start" },
                  children: "3.2\xd7",
                }),
              }),
              className: "framer-gnurlf",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "MTxbKHh_u",
              text: l8krc8cgY,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-kmegkv",
                  "data-styles-preset": "OsCWNv90r",
                  dir: "auto",
                  style: {
                    "--framer-text-alignment": "start",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, var(--token-e8be503c-36d3-4511-8754-07379d8f8757))",
                  },
                  children: "workflow throughput",
                }),
              }),
              className: "framer-qk1u4b",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "nop9jat2o",
              style: {
                "--extracted-r6o4lv":
                  "var(--token-e8be503c-36d3-4511-8754-07379d8f8757)",
              },
              text: OU5zgLyJt,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-awli9.framer-14cfowy, .framer-awli9 .framer-14cfowy { display: block; }",
  ".framer-awli9.framer-1ax6vdg { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 2px 0px 2px 16px; position: relative; width: 248px; }",
  ".framer-awli9 .framer-gnurlf, .framer-awli9 .framer-qk1u4b { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-awli9[data-border="true"]::after, .framer-awli9 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 60.5
 * @framerIntrinsicWidth 248
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"l8krc8cgY":"number","OU5zgLyJt":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerPxRVBBWIS = withCSS(Component, css, "framer-awli9");
export default FramerPxRVBBWIS;
FramerPxRVBBWIS.displayName = "Metrics card";
FramerPxRVBBWIS.defaultProps = { height: 60.5, width: 248 };
addPropertyControls(FramerPxRVBBWIS, {
  l8krc8cgY: {
    defaultValue: "3.2\xd7",
    displayTextArea: false,
    title: "Number",
    type: ControlType.String,
  },
  onl8krc8cgYChange: { changes: "l8krc8cgY", type: ControlType.ChangeHandler },
  OU5zgLyJt: {
    defaultValue: "workflow throughput",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onOU5zgLyJtChange: { changes: "OU5zgLyJt", type: ControlType.ChangeHandler },
});
addFonts(
  FramerPxRVBBWIS,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerPxRVBBWIS",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerVariables: '{"l8krc8cgY":"number","OU5zgLyJt":"title"}',
        framerIntrinsicHeight: "60.5",
        framerIntrinsicWidth: "248",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./PxRVBBWIS.map
