// Generated by Framer (089ff9b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  TickerItem,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withTickerFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Compass from "./ozy5h35fM.js";
import FileText from "./slcpTpvN_.js";
import Edit from "./X1jBwqdJ1.js";
import Music from "./QVsb0ONqC.js";
import Video from "./t7nwOy7JL.js";
import AlignLeft from "./oEfmVU5Y5.js";
import MessageCircle from "./xJIP_Y01J.js";
import * as sharedStyle from "./OsCWNv90r.js";
const FileTextFonts = getFonts(FileText);
const MusicFonts = getFonts(Music);
const VideoFonts = getFonts(Video);
const CompassFonts = getFonts(Compass);
const MotionDivWithTickerFX = withTickerFX(motion.div);
const EditFonts = getFonts(Edit);
const AlignLeftFonts = getFonts(AlignLeft);
const MessageCircleFonts = getFonts(MessageCircle);
const serializationHash = "framer-xPUJM";
const variantClassNames = { A2p5G7tdE: "framer-v-183hk9h" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "A2p5G7tdE",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-183hk9h",
            className,
            classNames,
          ),
          "data-framer-name": "1",
          layoutDependency: layoutDependency,
          layoutId: "A2p5G7tdE",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-a75fb687-8d00-4d08-9407-fce93f119924, rgb(246, 248, 247))",
            borderTopLeftRadius: 16,
            borderTopRightRadius: 16,
            ...style,
          },
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1cvfku",
            layoutDependency: layoutDependency,
            layoutId: "ZZFQCrzFV",
            transformTemplate: transformTemplate1,
            children: [
              /*#__PURE__*/ _jsxs(MotionDivWithTickerFX, {
                className: "framer-1o64dmn",
                layoutDependency: layoutDependency,
                layoutId: "bEUgkIo5A",
                tickerEffectAlign: "center",
                tickerEffectDirectionModifier: "default",
                tickerEffectDraggable: false,
                tickerEffectEnabled: true,
                tickerEffectGap: 16,
                tickerEffectHoverModifier: 100,
                tickerEffectOverflow: "visible",
                tickerEffectPosition: "relative",
                tickerEffectStackDirection: "row",
                tickerEffectVelocity: 50,
                children: [
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-4s5dbs",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "yDnN2zuri",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(FileText, {
                          animated: true,
                          className: "framer-p7h0fy",
                          layoutDependency: layoutDependency,
                          layoutId: "OPTJUsbU1",
                          style: { "--43q7um": "rgb(237, 149, 17)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Text",
                            }),
                          }),
                          className: "framer-1p9hiwf",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "N6lb0hqIn",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-qf32q4",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "xWZusnVPW",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(Music, {
                          animated: true,
                          className: "framer-h0yjum",
                          layoutDependency: layoutDependency,
                          layoutId: "xNcnlk6vl",
                          style: { "--43q7um": "rgb(230, 58, 28)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Audio",
                            }),
                          }),
                          className: "framer-x93bc7",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "vDjBYdalA",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-11gaagc",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "IhwxxrI2h",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(Video, {
                          animated: true,
                          className: "framer-8b0mb9",
                          layoutDependency: layoutDependency,
                          layoutId: "f3SlT9LFZ",
                          style: { "--43q7um": "rgb(179, 28, 230)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Video",
                            }),
                          }),
                          className: "framer-te9t7o",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "sTo_AKnDt",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-1yn9i0l",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "uub7NHhZJ",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(Compass, {
                          animated: true,
                          className: "framer-a38erm",
                          layoutDependency: layoutDependency,
                          layoutId: "HAOM6Ir41",
                          style: { "--43q7um": "rgb(28, 58, 230)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Web page",
                            }),
                          }),
                          className: "framer-1w58i8r",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "Mx6COL9iJ",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                ],
              }),
              /*#__PURE__*/ _jsxs(MotionDivWithTickerFX, {
                className: "framer-18jlnf2",
                layoutDependency: layoutDependency,
                layoutId: "cb7_UVRvV",
                tickerEffectAlign: "center",
                tickerEffectDirectionModifier: "reverse",
                tickerEffectDraggable: false,
                tickerEffectEnabled: true,
                tickerEffectGap: 16,
                tickerEffectHoverModifier: 100,
                tickerEffectOverflow: "visible",
                tickerEffectPosition: "relative",
                tickerEffectStackDirection: "row",
                tickerEffectVelocity: 50,
                children: [
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-1hz2k6o",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "vqipm8fqu",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(Edit, {
                          animated: true,
                          className: "framer-1rgnx3k",
                          layoutDependency: layoutDependency,
                          layoutId: "UlCMA7kcX",
                          style: { "--43q7um": "rgb(20, 195, 204)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Documents",
                            }),
                          }),
                          className: "framer-ulcqvw",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "YAtOxi1F6",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-q9drxc",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "VQhKQZhNy",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(AlignLeft, {
                          animated: true,
                          className: "framer-87koem",
                          layoutDependency: layoutDependency,
                          layoutId: "Spyz4ZL5M",
                          style: { "--43q7um": "rgb(42, 204, 20)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Spreadsheets",
                            }),
                          }),
                          className: "framer-18vgo7e",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "hfvkGoBOR",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                  /*#__PURE__*/ _jsx(TickerItem, {
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-184fesj",
                      "data-border": true,
                      "data-framer-name": "List",
                      layoutDependency: layoutDependency,
                      layoutId: "bpQfHIjiG",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      children: [
                        /*#__PURE__*/ _jsx(MessageCircle, {
                          animated: true,
                          className: "framer-1bpryzh",
                          layoutDependency: layoutDependency,
                          layoutId: "PYqAquyp2",
                          style: { "--43q7um": "rgb(2, 196, 183)" },
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              children: "Conversations",
                            }),
                          }),
                          className: "framer-1q3xdpu",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "M7pdqtiKX",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-xPUJM.framer-13cvsw6, .framer-xPUJM .framer-13cvsw6 { display: block; }",
  ".framer-xPUJM.framer-183hk9h { height: 353px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 310px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-xPUJM .framer-1cvfku { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 24px 0px 24px 0px; position: absolute; right: 0px; top: 50%; }",
  ".framer-xPUJM .framer-1o64dmn, .framer-xPUJM .framer-18jlnf2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-xPUJM .framer-4s5dbs, .framer-xPUJM .framer-qf32q4, .framer-xPUJM .framer-11gaagc, .framer-xPUJM .framer-1yn9i0l, .framer-xPUJM .framer-1hz2k6o, .framer-xPUJM .framer-q9drxc, .framer-xPUJM .framer-184fesj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 8px 16px 8px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-xPUJM .framer-p7h0fy, .framer-xPUJM .framer-h0yjum, .framer-xPUJM .framer-8b0mb9, .framer-xPUJM .framer-a38erm, .framer-xPUJM .framer-1rgnx3k, .framer-xPUJM .framer-87koem, .framer-xPUJM .framer-1bpryzh { aspect-ratio: 1 / 1; flex: none; height: auto; position: relative; width: 20px; }",
  ".framer-xPUJM .framer-1p9hiwf, .framer-xPUJM .framer-x93bc7, .framer-xPUJM .framer-te9t7o, .framer-xPUJM .framer-1w58i8r, .framer-xPUJM .framer-ulcqvw, .framer-xPUJM .framer-18vgo7e, .framer-xPUJM .framer-1q3xdpu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ...sharedStyle.css,
  '.framer-xPUJM[data-border="true"]::after, .framer-xPUJM [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 353
 * @framerIntrinsicWidth 310
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerqCXDZGj4q = withCSS(Component, css, "framer-xPUJM");
export default FramerqCXDZGj4q;
FramerqCXDZGj4q.displayName = "Multimodal card";
FramerqCXDZGj4q.defaultProps = { height: 353, width: 310 };
addFonts(
  FramerqCXDZGj4q,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...FileTextFonts,
    ...MusicFonts,
    ...VideoFonts,
    ...CompassFonts,
    ...EditFonts,
    ...AlignLeftFonts,
    ...MessageCircleFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerqCXDZGj4q",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "310",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicHeight: "353",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./qCXDZGj4q.map
