// Generated by Framer (c9b3949)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Image as Image1,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import TextWave from "./TextWave_Prod.js";
import RippleLoader from "./Square_loading.js";
import Check from "./ffUDbEmqv.js";
import * as sharedStyle from "./OsCWNv90r.js";
const RippleLoaderFonts = getFonts(RippleLoader);
const TextWaveFonts = getFonts(TextWave);
const CheckFonts = getFonts(Check);
const cycleOrder = [
  "v7PEsHkDR",
  "q8Ay5aMht",
  "Kc6uEL3pq",
  "hQfOODtpu",
  "KHfImUAlU",
  "KzWs2Rhkf",
];
const serializationHash = "framer-ATfJp";
const variantClassNames = {
  hQfOODtpu: "framer-v-h5b931",
  Kc6uEL3pq: "framer-v-149h9pd",
  KHfImUAlU: "framer-v-1q2tbt5",
  KzWs2Rhkf: "framer-v-10wsipn",
  q8Ay5aMht: "framer-v-fbfx2c",
  v7PEsHkDR: "framer-v-6qjnrw",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const E3jUzzWxL = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const numberToPixelString = (value) => {
  if (typeof value !== "number") return value;
  if (!Number.isFinite(value)) return undefined;
  return Math.max(0, value) + "px";
};
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  1: "v7PEsHkDR",
  2: "q8Ay5aMht",
  3: "Kc6uEL3pq",
  4: "hQfOODtpu",
  5: "KHfImUAlU",
  6: "KzWs2Rhkf",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, padding, width, ...props }) => {
  return {
    ...props,
    E3jUzzWxL: padding ?? props.E3jUzzWxL ?? "0px 24px 0px 24px",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "v7PEsHkDR",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, E3jUzzWxL, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "v7PEsHkDR",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppear6sju86 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("Kc6uEL3pq", true), 1e3);
  });
  const onAppear18u7ykf = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("hQfOODtpu", true), 1e3);
  });
  const onAppear18p3jyo = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("KHfImUAlU", true), 1e3);
  });
  const onAppearaokkea = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("KzWs2Rhkf", true), 1e3);
  });
  useOnVariantChange(baseVariant, {
    hQfOODtpu: onAppear18p3jyo,
    Kc6uEL3pq: onAppear18u7ykf,
    KHfImUAlU: onAppearaokkea,
    q8Ay5aMht: onAppear6sju86,
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (
      ["Kc6uEL3pq", "hQfOODtpu", "KHfImUAlU", "KzWs2Rhkf"].includes(baseVariant)
    )
      return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-6qjnrw",
            className,
            classNames,
          ),
          "data-framer-name": "1",
          layoutDependency: layoutDependency,
          layoutId: "v7PEsHkDR",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              hQfOODtpu: { "data-framer-name": "4", "data-highlight": true },
              Kc6uEL3pq: { "data-framer-name": "3", "data-highlight": true },
              KHfImUAlU: { "data-framer-name": "5", "data-highlight": true },
              KzWs2Rhkf: { "data-framer-name": "6" },
              q8Ay5aMht: { "data-framer-name": "2", "data-highlight": true },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1hwh214",
            "data-framer-name": "Overall container",
            layoutDependency: layoutDependency,
            layoutId: "wy1_vu3lS",
            style: { "--76zzdk": numberToPixelString(E3jUzzWxL) },
            transformTemplate: transformTemplate1,
            ...addPropertyOverrides(
              {
                hQfOODtpu: { transformTemplate: transformTemplate2 },
                Kc6uEL3pq: { transformTemplate: transformTemplate2 },
                KHfImUAlU: { transformTemplate: transformTemplate2 },
                KzWs2Rhkf: { transformTemplate: transformTemplate2 },
                q8Ay5aMht: { transformTemplate: transformTemplate2 },
              },
              baseVariant,
              gestureVariant,
            ),
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-frwqd3",
                "data-border": true,
                "data-framer-name": "Prompt Card",
                layoutDependency: layoutDependency,
                layoutId: "CHAYUJcXE",
                style: {
                  "--border-bottom-width": "1px",
                  "--border-color":
                    "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                  "--border-left-width": "1px",
                  "--border-right-width": "1px",
                  "--border-style": "solid",
                  "--border-top-width": "1px",
                  backdropFilter: "blur(10px)",
                  backgroundColor:
                    "var(--token-53d512fc-9508-4ca7-9593-aa4f8e122f95, rgba(255, 255, 255, 0.8))",
                  borderBottomLeftRadius: 18,
                  borderBottomRightRadius: 18,
                  borderTopLeftRadius: 18,
                  borderTopRightRadius: 18,
                  WebkitBackdropFilter: "blur(10px)",
                },
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1b4zlq0-container",
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        layoutDependency: layoutDependency,
                        layoutId: "pqyOze0mF-container",
                        nodeId: "pqyOze0mF",
                        rendersWithMotion: true,
                        scopeId: "qp1dFT5rB",
                        children: /*#__PURE__*/ _jsx(RippleLoader, {
                          background: "rgba(0, 0, 0, 0)",
                          cellSize: 6,
                          delay: 0.1,
                          duration: 1.5,
                          endColor:
                            "var(--token-cfa89a90-dbbb-4892-b359-3cd7c161f4ad, rgb(49, 91, 232))",
                          height: "100%",
                          id: "pqyOze0mF",
                          layoutId: "pqyOze0mF",
                          radius: 4,
                          spacing: 1,
                          startColor:
                            "var(--token-cfa89a90-dbbb-4892-b359-3cd7c161f4ad, rgb(49, 91, 232))",
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-tkmpuh-container",
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        layoutDependency: layoutDependency,
                        layoutId: "qKlvelU3h-container",
                        nodeId: "qKlvelU3h",
                        rendersWithMotion: true,
                        scopeId: "qp1dFT5rB",
                        children: /*#__PURE__*/ _jsx(TextWave, {
                          animation: {
                            delay: 0.2,
                            loop: true,
                            replay: true,
                            trigger: "appear",
                          },
                          colors: {
                            defaultColor:
                              "var(--token-2e8179f9-642e-40f6-a729-9879c38a7c7c, rgba(0, 0, 0, 0.4))",
                            waveInColor:
                              "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                          },
                          direction: "right",
                          font: {
                            fontFamily:
                              '"Geist", "Geist Placeholder", sans-serif',
                            fontSize: "16px",
                            fontStyle: "normal",
                            fontWeight: 400,
                            letterSpacing: "-0.3px",
                            lineHeight: "16px",
                            textAlign: "left",
                          },
                          glow: {
                            blur: 0,
                            color:
                              "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                          },
                          height: "100%",
                          id: "qKlvelU3h",
                          layoutId: "qKlvelU3h",
                          origin: "center",
                          per: "character",
                          resize: false,
                          speed: 80,
                          tag: "p",
                          text: "Summarising spreadsheet",
                          userSelect: false,
                          waveScale: 1.01,
                          waveWidth: 30,
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                ],
              }),
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-1kl1j4c-container",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layoutDependency: layoutDependency,
                  layoutId: "Kaz0HUENP-container",
                  nodeId: "Kaz0HUENP",
                  rendersWithMotion: true,
                  scopeId: "qp1dFT5rB",
                  style: { opacity: 0 },
                  variants: {
                    hQfOODtpu: { opacity: 1 },
                    Kc6uEL3pq: { opacity: 1 },
                    KHfImUAlU: { opacity: 1 },
                    KzWs2Rhkf: { opacity: 1 },
                    q8Ay5aMht: { opacity: 1 },
                  },
                  children: /*#__PURE__*/ _jsx(TextWave, {
                    animation: {
                      delay: 0.2,
                      loop: true,
                      replay: true,
                      trigger: "appear",
                    },
                    colors: {
                      defaultColor:
                        "var(--token-2e8179f9-642e-40f6-a729-9879c38a7c7c, rgba(0, 0, 0, 0.4))",
                      waveInColor:
                        "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                    },
                    direction: "right",
                    font: {
                      fontFamily: '"Geist", "Geist Placeholder", sans-serif',
                      fontSize: "16px",
                      fontStyle: "normal",
                      fontWeight: 400,
                      letterSpacing: "-0.3px",
                      lineHeight: "16px",
                      textAlign: "left",
                    },
                    glow: {
                      blur: 0,
                      color:
                        "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                    },
                    height: "100%",
                    id: "Kaz0HUENP",
                    layoutId: "Kaz0HUENP",
                    origin: "center",
                    per: "character",
                    resize: false,
                    speed: 80,
                    tag: "p",
                    text: "Selecting model",
                    userSelect: false,
                    waveScale: 1.01,
                    waveWidth: 30,
                    width: "100%",
                  }),
                }),
              }),
              isDisplayed() &&
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-1jilwiq",
                  "data-framer-name": "Model container",
                  layoutDependency: layoutDependency,
                  layoutId: "GjZ1nv1u_",
                  children: [
                    isDisplayed() &&
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1dujn8s",
                        "data-framer-name": "Model info",
                        layoutDependency: layoutDependency,
                        layoutId: "XeTy6XBHQ",
                        children: [
                          /*#__PURE__*/ _jsx(Image1, {
                            background: {
                              alt: "",
                              fit: "fill",
                              pixelHeight: 100,
                              pixelWidth: 100,
                              sizes: "24px",
                              src: "https://framerusercontent.com/images/8KaKKxU7M28Rzb4GcWcA3KaCnQ4.png?width=100&height=100",
                            },
                            className: "framer-1788p5m",
                            "data-framer-name": "Image container",
                            layoutDependency: layoutDependency,
                            layoutId: "oKeqt5C8p",
                            style: {
                              borderBottomLeftRadius: 1e3,
                              borderBottomRightRadius: 1e3,
                              borderTopLeftRadius: 1e3,
                              borderTopRightRadius: 1e3,
                            },
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-kmegkv",
                                "data-styles-preset": "OsCWNv90r",
                                dir: "auto",
                                children: "Chatgpt",
                              }),
                            }),
                            className: "framer-11vw9y5",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "YSLJy7cOE",
                            style: {
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                    isDisplayed() &&
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-uo1hq3",
                        "data-framer-name": "Model info",
                        layoutDependency: layoutDependency,
                        layoutId: "aZZYx8DQY",
                        children: [
                          /*#__PURE__*/ _jsx(Image1, {
                            background: {
                              alt: "",
                              fit: "fill",
                              intrinsicHeight: 100,
                              intrinsicWidth: 100,
                              pixelHeight: 100,
                              pixelWidth: 100,
                              sizes: "24px",
                              src: "https://framerusercontent.com/images/D78PPxXxhqJnQlCBn2cmf5ueuQ.png?width=100&height=100",
                            },
                            className: "framer-1crojzz",
                            "data-framer-name": "Image container",
                            layoutDependency: layoutDependency,
                            layoutId: "DENvzy8UU",
                            style: {
                              borderBottomLeftRadius: 1e3,
                              borderBottomRightRadius: 1e3,
                              borderTopLeftRadius: 1e3,
                              borderTopRightRadius: 1e3,
                            },
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-kmegkv",
                                "data-styles-preset": "OsCWNv90r",
                                dir: "auto",
                                children: "Claude",
                              }),
                            }),
                            className: "framer-1sbgov2",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "STbBl5cEo",
                            style: {
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(Check, {
                            animated: true,
                            className: "framer-103iiio",
                            layoutDependency: layoutDependency,
                            layoutId: "aKNNjjTIm",
                            style: {
                              "--43q7um": "rgb(2, 194, 59)",
                              opacity: 1,
                              scale: 1,
                            },
                            variants: {
                              hQfOODtpu: { opacity: 0, scale: 0 },
                              Kc6uEL3pq: { opacity: 0, scale: 0 },
                              KHfImUAlU: { opacity: 0, scale: 1 },
                              KzWs2Rhkf: { opacity: 1, scale: 1 },
                            },
                            ...addPropertyOverrides(
                              {
                                Kc6uEL3pq: {
                                  transformTemplate: transformTemplate1,
                                },
                                KHfImUAlU: {
                                  transformTemplate: transformTemplate1,
                                },
                                KzWs2Rhkf: {
                                  transformTemplate: transformTemplate1,
                                },
                              },
                              baseVariant,
                              gestureVariant,
                            ),
                          }),
                        ],
                      }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-9ya73t",
                      "data-framer-name": "Selector",
                      layoutDependency: layoutDependency,
                      layoutId: "v92aHWaUo",
                      style: {
                        "--border-bottom-width": "0px",
                        "--border-color": "rgba(0, 0, 0, 0)",
                        "--border-left-width": "0px",
                        "--border-right-width": "0px",
                        "--border-style": "solid",
                        "--border-top-width": "0px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 12,
                        borderBottomRightRadius: 12,
                        borderTopLeftRadius: 12,
                        borderTopRightRadius: 12,
                        opacity: 1,
                        scale: 1,
                      },
                      variants: {
                        hQfOODtpu: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          opacity: 1,
                          scale: 1,
                        },
                        Kc6uEL3pq: { opacity: 0, scale: 0 },
                        KHfImUAlU: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          opacity: 1,
                          scale: 1,
                        },
                        KzWs2Rhkf: {
                          "--border-bottom-width": "1px",
                          "--border-color":
                            "var(--token-8144f193-de43-475d-87ea-e22ad062944c, rgba(0, 0, 0, 0.1))",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          opacity: 1,
                          scale: 1,
                        },
                      },
                      ...addPropertyOverrides(
                        {
                          hQfOODtpu: { "data-border": true },
                          KHfImUAlU: { "data-border": true },
                          KzWs2Rhkf: { "data-border": true },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  ],
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-ATfJp.framer-16dncio, .framer-ATfJp .framer-16dncio { display: block; }",
  ".framer-ATfJp.framer-6qjnrw { height: 387px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 342px; }",
  ".framer-ATfJp .framer-1hwh214 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: var(--76zzdk); position: absolute; right: 0px; top: 50%; }",
  ".framer-ATfJp .framer-frwqd3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; padding: 16px; position: relative; width: 100%; z-index: 1; }",
  ".framer-ATfJp .framer-1b4zlq0-container, .framer-ATfJp .framer-103iiio { aspect-ratio: 1 / 1; flex: none; height: auto; position: relative; width: 24px; }",
  ".framer-ATfJp .framer-tkmpuh-container, .framer-ATfJp .framer-1kl1j4c-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-ATfJp .framer-1jilwiq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; min-height: 200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-ATfJp .framer-1dujn8s, .framer-ATfJp .framer-uo1hq3 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 12px 16px 12px 16px; position: relative; width: 1px; z-index: 1; }",
  ".framer-ATfJp .framer-1788p5m { aspect-ratio: 1 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 24px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-ATfJp .framer-11vw9y5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
  ".framer-ATfJp .framer-1crojzz { aspect-ratio: 1 / 1; flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 24px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-ATfJp .framer-1sbgov2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-ATfJp .framer-9ya73t { flex: none; height: 50px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
  ".framer-ATfJp.framer-v-fbfx2c .framer-1hwh214 { left: 50%; right: unset; top: 44%; width: 100%; }",
  ".framer-ATfJp.framer-v-fbfx2c .framer-frwqd3, .framer-ATfJp.framer-v-149h9pd .framer-frwqd3, .framer-ATfJp.framer-v-h5b931 .framer-frwqd3, .framer-ATfJp.framer-v-1q2tbt5 .framer-frwqd3, .framer-ATfJp.framer-v-10wsipn .framer-frwqd3 { order: 0; }",
  ".framer-ATfJp.framer-v-fbfx2c .framer-1kl1j4c-container, .framer-ATfJp.framer-v-149h9pd .framer-1kl1j4c-container, .framer-ATfJp.framer-v-h5b931 .framer-1kl1j4c-container, .framer-ATfJp.framer-v-1q2tbt5 .framer-1kl1j4c-container, .framer-ATfJp.framer-v-10wsipn .framer-1kl1j4c-container { order: 1; }",
  ".framer-ATfJp.framer-v-149h9pd .framer-1hwh214, .framer-ATfJp.framer-v-h5b931 .framer-1hwh214, .framer-ATfJp.framer-v-1q2tbt5 .framer-1hwh214, .framer-ATfJp.framer-v-10wsipn .framer-1hwh214 { left: 50%; right: unset; width: 100%; }",
  ".framer-ATfJp.framer-v-149h9pd .framer-1jilwiq, .framer-ATfJp.framer-v-h5b931 .framer-1jilwiq, .framer-ATfJp.framer-v-1q2tbt5 .framer-1jilwiq, .framer-ATfJp.framer-v-10wsipn .framer-1jilwiq { flex-direction: column; min-height: unset; order: 2; }",
  ".framer-ATfJp.framer-v-149h9pd .framer-1dujn8s, .framer-ATfJp.framer-v-149h9pd .framer-uo1hq3, .framer-ATfJp.framer-v-h5b931 .framer-1dujn8s, .framer-ATfJp.framer-v-h5b931 .framer-uo1hq3, .framer-ATfJp.framer-v-1q2tbt5 .framer-1dujn8s, .framer-ATfJp.framer-v-1q2tbt5 .framer-uo1hq3, .framer-ATfJp.framer-v-10wsipn .framer-1dujn8s, .framer-ATfJp.framer-v-10wsipn .framer-uo1hq3 { flex: none; width: 100%; }",
  ".framer-ATfJp.framer-v-149h9pd .framer-103iiio, .framer-ATfJp.framer-v-1q2tbt5 .framer-103iiio, .framer-ATfJp.framer-v-10wsipn .framer-103iiio { position: absolute; right: 16px; top: 51%; z-index: 1; }",
  ".framer-ATfJp.framer-v-1q2tbt5 .framer-9ya73t, .framer-ATfJp.framer-v-10wsipn .framer-9ya73t { top: 50px; }",
  ...sharedStyle.css,
  '.framer-ATfJp[data-border="true"]::after, .framer-ATfJp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 387
 * @framerIntrinsicWidth 342
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"q8Ay5aMht":{"layout":["fixed","fixed"]},"Kc6uEL3pq":{"layout":["fixed","fixed"]},"hQfOODtpu":{"layout":["fixed","fixed"]},"KHfImUAlU":{"layout":["fixed","fixed"]},"KzWs2Rhkf":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"E3jUzzWxL":"padding"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerqp1dFT5rB = withCSS(Component, css, "framer-ATfJp");
export default Framerqp1dFT5rB;
Framerqp1dFT5rB.displayName = "Capability card";
Framerqp1dFT5rB.defaultProps = { height: 387, width: 342 };
addPropertyControls(Framerqp1dFT5rB, {
  variant: {
    options: [
      "v7PEsHkDR",
      "q8Ay5aMht",
      "Kc6uEL3pq",
      "hQfOODtpu",
      "KHfImUAlU",
      "KzWs2Rhkf",
    ],
    optionTitles: ["1", "2", "3", "4", "5", "6"],
    title: "Variant",
    type: ControlType.Enum,
  },
  E3jUzzWxL: {
    defaultValue: "0px 24px 0px 24px",
    title: "Padding",
    type: ControlType.Padding,
  },
});
addFonts(
  Framerqp1dFT5rB,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Geist",
          source: "google",
          style: "normal",
          uiFamilyName: "Geist",
          url: "https://fonts.gstatic.com/s/geist/v5/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...RippleLoaderFonts,
    ...TextWaveFonts,
    ...CheckFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerqp1dFT5rB",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"q8Ay5aMht":{"layout":["fixed","fixed"]},"Kc6uEL3pq":{"layout":["fixed","fixed"]},"hQfOODtpu":{"layout":["fixed","fixed"]},"KHfImUAlU":{"layout":["fixed","fixed"]},"KzWs2Rhkf":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "387",
        framerIntrinsicWidth: "342",
        framerAutoSizeImages: "true",
        framerVariables: '{"E3jUzzWxL":"padding"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./qp1dFT5rB.map
