// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask =
  'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 15 L 0 2 L 12 0 L 12 13" fill="transparent" height="15px" id="MAYp4kmar" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(9 3)" width="12px"/><path d="M 0 3 C 0 1.343 1.343 0 3 0 C 4.657 0 6 1.343 6 3 C 6 4.657 4.657 6 3 6 C 1.343 6 0 4.657 0 3 Z" fill="transparent" height="6px" id="Sn7qox4yf" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(3 15)" width="6px"/><path d="M 0 3 C 0 1.343 1.343 0 3 0 C 4.657 0 6 1.343 6 3 C 6 4.657 4.657 6 3 6 C 1.343 6 0 4.657 0 3 Z" fill="transparent" height="6px" id="E1TIOA8AX" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(15 13)" width="6px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ height, id, stroke, width, ...props }) => {
  return { ...props, UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)" };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
    getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-uLi5K", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--43q7um": UO5clYVeQ, ...style },
  });
});
const css = [
  `.framer-uLi5K { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"UO5clYVeQ":"stroke"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Music","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-uLi5K");
Icon.displayName = "Music";
export default Icon;
addPropertyControls(Icon, {
  UO5clYVeQ: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Stroke",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerVariables: '{"UO5clYVeQ":"stroke"}',
        framerContractVersion: "1",
        framerVector:
          '{"name":"Music","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}',
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerIntrinsicWidth: "24",
        framerDisableUnlink: "true",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerIntrinsicHeight: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
