// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask =
  'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 10 0 L 2 0 C 0.895 0 0 0.895 0 2 L 0 18 C 0 19.105 0.895 20 2 20 L 14 20 C 15.105 20 16 19.105 16 18 L 16 6 Z" fill="transparent" height="20px" id="IwG8rD_Ad" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(4 2)" width="16px"/><path d="M 0 0 L 0 6 L 6 6" fill="transparent" height="6px" id="cYvtdwwIa" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(14 2)" width="6px"/><path d="M 8 0 L 0 0" fill="transparent" height="1px" id="J5RR35tvM" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(8 13)" width="8px"/><path d="M 8 0 L 0 0" fill="transparent" height="1px" id="WlvY0hwKl" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(8 17)" width="8px"/><path d="M 2 0 L 1 0 L 0 0" fill="transparent" height="1px" id="zJaUQcHSu" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(8 9)" width="2px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ height, id, stroke, width, ...props }) => {
  return { ...props, UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)" };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
    getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-tv1Fx", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--43q7um": UO5clYVeQ, ...style },
  });
});
const css = [
  `.framer-tv1Fx { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"UO5clYVeQ":"stroke"}
 * @framerImmutableVariables true
 * @framerVector {"name":"File Text","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-tv1Fx");
Icon.displayName = "File Text";
export default Icon;
addPropertyControls(Icon, {
  UO5clYVeQ: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Stroke",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVariables: '{"UO5clYVeQ":"stroke"}',
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerDisableUnlink: "true",
        framerIntrinsicWidth: "24",
        framerImmutableVariables: "true",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerIntrinsicHeight: "24",
        framerContractVersion: "1",
        framerVector:
          '{"name":"File Text","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
