// Generated by Framer (089ff9b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getPropertyControls,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import DottedIcon from "./DottedIcon.js";
import * as sharedStyle1 from "./OsCWNv90r.js";
import * as sharedStyle from "./PVAJnpDa2.js";
const DottedIconFonts = getFonts(DottedIcon);
const DottedIconControls = getPropertyControls(DottedIcon);
const cycleOrder = ["IOFRMGkFA", "brhoJTL4S", "RguhoTqFw"];
const serializationHash = "framer-JFz8X";
const variantClassNames = {
  brhoJTL4S: "framer-v-1a0pdpg",
  IOFRMGkFA: "framer-v-7v5g9o",
  RguhoTqFw: "framer-v-mqjrza",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const qsf_jzvJo = undefined;
const Z5vgYAPQH = undefined;
const tXbZtYZqx = undefined;
const tsG1XIgR5 = undefined;
const I2tQz0P2f = undefined;
const BbwBbkHIn = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "IOFRMGkFA",
  phone: "RguhoTqFw",
  Tablet: "brhoJTL4S",
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  density,
  description,
  height,
  id,
  industryName,
  pixelSize,
  pNGSVG,
  threshold,
  width,
  ...props
}) => {
  return {
    ...props,
    BbwBbkHIn:
      description ??
      props.BbwBbkHIn ??
      "Organize information, support reviews, and streamline recurring reporting.",
    I2tQz0P2f: industryName ?? props.I2tQz0P2f ?? "Financial services",
    qsf_jzvJo:
      pNGSVG ??
      props.qsf_jzvJo ??
      "https://framerusercontent.com/assets/JXfbymshMLyfsl2323zgdqBGL4.svg",
    tsG1XIgR5: threshold ?? props.tsG1XIgR5 ?? 0.46,
    tXbZtYZqx: pixelSize ?? props.tXbZtYZqx ?? 1,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "IOFRMGkFA",
    Z5vgYAPQH: density ?? props.Z5vgYAPQH ?? 18,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    I2tQz0P2f,
    BbwBbkHIn,
    qsf_jzvJo,
    Z5vgYAPQH,
    tXbZtYZqx,
    tsG1XIgR5,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "IOFRMGkFA",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-7v5g9o",
            className,
            classNames,
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "IOFRMGkFA",
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 16,
            borderBottomRightRadius: 16,
            borderTopLeftRadius: 16,
            borderTopRightRadius: 16,
            ...style,
          },
          ...addPropertyOverrides(
            {
              brhoJTL4S: { "data-framer-name": "Tablet" },
              RguhoTqFw: { "data-framer-name": "phone" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-v5wgs2-container",
                "data-code-component-plugin-id": "api",
                isAuthoredByUser: true,
                layoutDependency: layoutDependency,
                layoutId: "NR1hg8rBU-container",
                nodeId: "NR1hg8rBU",
                rendersWithMotion: true,
                scopeId: "slkat30Sb",
                children: /*#__PURE__*/ _jsx(DottedIcon, {
                  activeColor:
                    "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                  ariaLabel: "Dotted icon",
                  background:
                    "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                  columns: Z5vgYAPQH,
                  detection: "alpha",
                  dotScale: 0.61,
                  fit: "contain",
                  glow: 0,
                  gradientAngle: 16,
                  gradientColor1: "rgb(0, 229, 255)",
                  gradientColor2:
                    "var(--token-b48b7134-7ad2-4f07-b792-c7a8003d791a, rgb(1, 43, 255))",
                  gradientColor3:
                    "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255))",
                  gradientColor4:
                    "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255))",
                  gradientColor5:
                    "var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255))",
                  height: "100%",
                  id: "NR1hg8rBU",
                  inactiveColor:
                    "var(--token-22d3f34c-2981-4b25-b181-148f3f405183, rgba(255, 255, 255, 0.05))",
                  inactiveOpacity: 0,
                  invert: false,
                  layoutId: "NR1hg8rBU",
                  matrixColorMode: "gradient",
                  padding: 0,
                  pixelRadius: 0,
                  pixelScale: tXbZtYZqx,
                  radius: 0,
                  renderStyle: "pixels",
                  shimmer: true,
                  shimmerAngle: -50,
                  shimmerColor:
                    "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                  shimmerDuration: 1.8,
                  shimmerIntensity: 0.4,
                  shimmerWidth: 0.5,
                  source: qsf_jzvJo,
                  style: { height: "100%", width: "100%" },
                  threshold: tsG1XIgR5,
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1u2uvc5",
              layoutDependency: layoutDependency,
              layoutId: "LK2Ck6LIi",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h5, {
                      className: "framer-styles-preset-d27mg8",
                      "data-styles-preset": "PVAJnpDa2",
                      dir: "auto",
                      style: {
                        "--framer-text-alignment": "start",
                        "--framer-text-color":
                          "var(--extracted-1lwpl3i, var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255)))",
                      },
                      children: "Financial services",
                    }),
                  }),
                  className: "framer-15lvlwh",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "WlDd498Va",
                  style: {
                    "--extracted-1lwpl3i":
                      "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  text: I2tQz0P2f,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-kmegkv",
                      "data-styles-preset": "OsCWNv90r",
                      dir: "auto",
                      style: {
                        "--framer-text-alignment": "start",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-bfdae1e4-91e8-463a-8cf8-3968004590a9, rgba(255, 255, 255, 0.6)))",
                      },
                      children:
                        "Organize information, support reviews, and streamline recurring reporting.",
                    }),
                  }),
                  className: "framer-a1b9uq",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "iGCEXLeqm",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-bfdae1e4-91e8-463a-8cf8-3968004590a9, rgba(255, 255, 255, 0.6))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  text: BbwBbkHIn,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-JFz8X.framer-16qe2o9, .framer-JFz8X .framer-16qe2o9 { display: block; }",
  ".framer-JFz8X.framer-7v5g9o { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 32px; position: relative; width: 363px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-JFz8X .framer-v5wgs2-container { aspect-ratio: 1 / 1; flex: none; height: auto; position: relative; width: 80px; }",
  ".framer-JFz8X .framer-1u2uvc5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-JFz8X .framer-15lvlwh { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-JFz8X .framer-a1b9uq { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-JFz8X.framer-v-1a0pdpg.framer-7v5g9o { gap: 32px; padding: 24px; }",
  ".framer-JFz8X.framer-v-1a0pdpg .framer-v5wgs2-container { width: 60px; }",
  ".framer-JFz8X.framer-v-mqjrza.framer-7v5g9o { gap: 24px; padding: 24px; }",
  ".framer-JFz8X.framer-v-mqjrza .framer-v5wgs2-container { width: 40px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 268
 * @framerIntrinsicWidth 362.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"brhoJTL4S":{"layout":["fixed","auto"]},"RguhoTqFw":{"layout":["fixed","auto"]}}}
 * @framerVariables {"I2tQz0P2f":"industryName","BbwBbkHIn":"description","qsf_jzvJo":"pNGSVG","Z5vgYAPQH":"density","tXbZtYZqx":"pixelSize","tsG1XIgR5":"threshold"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerslkat30Sb = withCSS(Component, css, "framer-JFz8X");
export default Framerslkat30Sb;
Framerslkat30Sb.displayName = "Industry card";
Framerslkat30Sb.defaultProps = { height: 268, width: 362.5 };
addPropertyControls(Framerslkat30Sb, {
  variant: {
    options: ["IOFRMGkFA", "brhoJTL4S", "RguhoTqFw"],
    optionTitles: ["Desktop", "Tablet", "phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  I2tQz0P2f: {
    defaultValue: "Financial services",
    displayTextArea: false,
    title: "Industry name",
    type: ControlType.String,
  },
  onI2tQz0P2fChange: { changes: "I2tQz0P2f", type: ControlType.ChangeHandler },
  BbwBbkHIn: {
    defaultValue:
      "Organize information, support reviews, and streamline recurring reporting.",
    displayTextArea: false,
    title: "Description",
    type: ControlType.String,
  },
  onBbwBbkHInChange: { changes: "BbwBbkHIn", type: ControlType.ChangeHandler },
  qsf_jzvJo: DottedIconControls?.["source"] && {
    ...DottedIconControls["source"],
    __defaultAssetReference:
      "data:framer/asset-reference,JXfbymshMLyfsl2323zgdqBGL4.svg?originalFilename=building-08.svg",
    description: undefined,
    hidden: undefined,
    title: "PNG SVG",
  },
  onqsf_jzvJoChange: { changes: "qsf_jzvJo", type: ControlType.ChangeHandler },
  Z5vgYAPQH: {
    defaultValue: 18,
    displayStepper: true,
    max: 80,
    min: 6,
    step: 1,
    title: "Density",
    type: ControlType.Number,
  },
  onZ5vgYAPQHChange: { changes: "Z5vgYAPQH", type: ControlType.ChangeHandler },
  tXbZtYZqx: {
    defaultValue: 1,
    max: 1,
    min: 0.1,
    step: 0.01,
    title: "Pixel Size",
    type: ControlType.Number,
  },
  ontXbZtYZqxChange: { changes: "tXbZtYZqx", type: ControlType.ChangeHandler },
  tsG1XIgR5: {
    defaultValue: 0.46,
    max: 0.95,
    min: 0,
    step: 0.01,
    title: "Threshold",
    type: ControlType.Number,
  },
  ontsG1XIgR5Change: { changes: "tsG1XIgR5", type: ControlType.ChangeHandler },
});
addFonts(
  Framerslkat30Sb,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...DottedIconFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerslkat30Sb",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerIntrinsicHeight: "268",
        framerVariables:
          '{"I2tQz0P2f":"industryName","BbwBbkHIn":"description","qsf_jzvJo":"pNGSVG","Z5vgYAPQH":"density","tXbZtYZqx":"pixelSize","tsG1XIgR5":"threshold"}',
        framerIntrinsicWidth: "362.5",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"brhoJTL4S":{"layout":["fixed","auto"]},"RguhoTqFw":{"layout":["fixed","auto"]}}}',
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./slkat30Sb.map
