// Generated by Framer (c9b3949)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-Nb7zH .framer-styles-preset-1t2prp2:not(.rich-text-wrapper), .framer-Nb7zH .framer-styles-preset-1t2prp2.rich-text-wrapper a { --framer-link-hover-text-color: var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, #ffffff); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-53d512fc-9508-4ca7-9593-aa4f8e122f95, rgba(255, 255, 255, 0.8)); }",
];
export const className = "framer-Nb7zH";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
