// Generated by Framer (c9b3949)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getPropertyControls,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ArrowRight from "./gXjG4ReaI.js";
import SlotCounter from "./SlotCounter.js";
import * as sharedStyle from "./bRNm9CgLj.js";
import * as sharedStyle2 from "./OsCWNv90r.js";
import * as sharedStyle1 from "./VMB1MMLPM.js";
import PricingList from "./EuWUBM8Ks.js";
import Button from "./Jh9jZPCX6.js";
const MotionDivWithFX = withFX(motion.div);
const SlotCounterFonts = getFonts(SlotCounter);
const PricingListFonts = getFonts(PricingList);
const ButtonFonts = getFonts(Button);
const ButtonControls = getPropertyControls(Button);
const serializationHash = "framer-ojBS5";
const variantClassNames = { H9DoIxkyo: "framer-v-1q3xcpt" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const icLcyvEbo = undefined;
const nXi9DWiJi = undefined;
const viOlM9VYn = undefined;
const HIb36ulNU = undefined;
const Kjgt9_VjS = undefined;
const rvjiqNekA = undefined;
const RhGdP9vsz = undefined;
const rLjb1sTpM = undefined;
const KGukpFXRd = undefined;
const EtXvqbnrf = undefined;
const B8WqQafkB = undefined;
const Z7KoJzaTd = undefined;
const VNw9l7uWS = undefined;
const setrvjiqNekA = undefined;
const setRhGdP9vsz = undefined;
const setrLjb1sTpM = undefined;
const setKGukpFXRd = undefined;
const setEtXvqbnrf = undefined;
const setZ7KoJzaTd = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  delay: 0,
  duration: 1,
  ease: [0, 0, 1, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 140,
  y: 50,
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = {
  "Desktop/primary light": "AfZO288ir",
  "Desktop/primary": "n1gMtcmI9",
  "Desktop/primary/small": "YnCyd7g0P",
  "Desktop/Secondary": "jlYR3ckV6",
  "Desktop/secondary/small": "L4yW9kxuA",
};
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({
  buttonVariant,
  feature1,
  feature2,
  feature3,
  feature4,
  feature5,
  height,
  id,
  label,
  link,
  period,
  planDescription,
  planName,
  popularTag,
  value,
  width,
  ...props
}) => {
  return {
    ...props,
    B8WqQafkB:
      humanReadableEnumMap[buttonVariant] ??
      buttonVariant ??
      props.B8WqQafkB ??
      "jlYR3ckV6",
    EtXvqbnrf: feature5 ?? props.EtXvqbnrf ?? "Personal workspace",
    HIb36ulNU: period ?? props.HIb36ulNU ?? "/ month",
    icLcyvEbo: planName ?? props.icLcyvEbo ?? "Starter",
    KGukpFXRd: feature4 ?? props.KGukpFXRd ?? "Personal workspace",
    Kjgt9_VjS:
      planDescription ??
      props.Kjgt9_VjS ??
      "For individuals organizing and automating everyday work.",
    nXi9DWiJi: popularTag ?? props.nXi9DWiJi ?? true,
    RhGdP9vsz: feature2 ?? props.RhGdP9vsz ?? "Personal workspace",
    rLjb1sTpM: feature3 ?? props.rLjb1sTpM ?? "Personal workspace",
    rvjiqNekA: feature1 ?? props.rvjiqNekA ?? "Personal workspace",
    viOlM9VYn: value ?? props.viOlM9VYn ?? 99,
    VNw9l7uWS: link ?? props.VNw9l7uWS,
    Z7KoJzaTd: label ?? props.Z7KoJzaTd ?? "Get started",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    nXi9DWiJi,
    B8WqQafkB,
    Z7KoJzaTd: externalZ7KoJzaTd,
    onZ7KoJzaTdChange: setExternalZ7KoJzaTd,
    HIb36ulNU,
    viOlM9VYn,
    rvjiqNekA: externalrvjiqNekA,
    onrvjiqNekAChange: setExternalrvjiqNekA,
    RhGdP9vsz: externalRhGdP9vsz,
    onRhGdP9vszChange: setExternalRhGdP9vsz,
    rLjb1sTpM: externalrLjb1sTpM,
    onrLjb1sTpMChange: setExternalrLjb1sTpM,
    KGukpFXRd: externalKGukpFXRd,
    onKGukpFXRdChange: setExternalKGukpFXRd,
    EtXvqbnrf: externalEtXvqbnrf,
    onEtXvqbnrfChange: setExternalEtXvqbnrf,
    icLcyvEbo,
    Kjgt9_VjS,
    VNw9l7uWS,
    ...restProps
  } = getProps(props);
  const [Z7KoJzaTd, setZ7KoJzaTd] = useStateVariable(
    externalZ7KoJzaTd,
    setExternalZ7KoJzaTd,
  );
  const [rvjiqNekA, setrvjiqNekA] = useStateVariable(
    externalrvjiqNekA,
    setExternalrvjiqNekA,
  );
  const [RhGdP9vsz, setRhGdP9vsz] = useStateVariable(
    externalRhGdP9vsz,
    setExternalRhGdP9vsz,
  );
  const [rLjb1sTpM, setrLjb1sTpM] = useStateVariable(
    externalrLjb1sTpM,
    setExternalrLjb1sTpM,
  );
  const [KGukpFXRd, setKGukpFXRd] = useStateVariable(
    externalKGukpFXRd,
    setExternalKGukpFXRd,
  );
  const [EtXvqbnrf, setEtXvqbnrf] = useStateVariable(
    externalEtXvqbnrf,
    setExternalEtXvqbnrf,
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "H9DoIxkyo",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1q3xcpt",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "H9DoIxkyo",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color":
              "var(--token-8144f193-de43-475d-87ea-e22ad062944c)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor:
              "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b)",
            borderBottomLeftRadius: 22,
            borderBottomRightRadius: 22,
            borderTopLeftRadius: 22,
            borderTopRightRadius: 22,
            ...style,
          },
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1o3q9jv",
            "data-border": true,
            "data-framer-name": "Starter plan",
            layoutDependency: layoutDependency,
            layoutId: "njDlcr_6I",
            style: {
              "--border-bottom-width": "1px",
              "--border-color":
                "var(--token-8144f193-de43-475d-87ea-e22ad062944c)",
              "--border-left-width": "1px",
              "--border-right-width": "1px",
              "--border-style": "solid",
              "--border-top-width": "1px",
              backgroundColor:
                "var(--token-a75fb687-8d00-4d08-9407-fce93f119924, rgb(246, 248, 247))",
              borderBottomLeftRadius: 16,
              borderBottomRightRadius: 16,
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
            },
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-r0fy2x",
                "data-framer-name": "Starter heading",
                layoutDependency: layoutDependency,
                layoutId: "Y0x83pAsh",
                children: /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-17c72qm",
                  "data-framer-name": "Starter name",
                  layoutDependency: layoutDependency,
                  layoutId: "Gs4ckpB1o",
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1ittrum",
                      "data-framer-name": "Plan name",
                      layoutDependency: layoutDependency,
                      layoutId: "lYB1qnlwu",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h4, {
                            className: "framer-styles-preset-1yb596b",
                            "data-styles-preset": "bRNm9CgLj",
                            dir: "auto",
                            children: "Starter",
                          }),
                        }),
                        className: "framer-1cq72z8",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ykEetJfjE",
                        text: icLcyvEbo,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                    nXi9DWiJi !== false &&
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-ep8xlz",
                        "data-framer-name": "Tag - Squared small before shine",
                        layoutDependency: layoutDependency,
                        layoutId: "u7ZReASep",
                        style: {
                          background:
                            "linear-gradient(135deg, var(--token-b39a48ae-2f48-4067-9b92-9d8fcfd251a1, rgb(9, 174, 255)) 0%, var(--token-fd2642e7-ea40-4298-8994-88ab422747df, rgb(9, 153, 224)) 100%)",
                          borderBottomLeftRadius: 100,
                          borderBottomRightRadius: 100,
                          borderTopLeftRadius: 100,
                          borderTopRightRadius: 100,
                          boxShadow:
                            "0px 0.24145061431045178px 0.24145061431045178px -1.875px rgba(0, 0, 0, 0.24), 0px 2px 2px -3.75px rgba(0, 0, 0, 0.09)",
                        },
                        children: [
                          /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-16anaen",
                            "data-framer-name": "Text + badge container",
                            layoutDependency: layoutDependency,
                            layoutId: "poS07KZRF",
                            children: /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  className: "framer-styles-preset-m10r77",
                                  "data-styles-preset": "VMB1MMLPM",
                                  dir: "auto",
                                  style: {
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255)))",
                                  },
                                  children: "Most popular",
                                }),
                              }),
                              className: "framer-stuttq",
                              fonts: ["Inter"],
                              layoutDependency: layoutDependency,
                              layoutId: "FnyTlVQr5",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b, rgb(255, 255, 255))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                              },
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                          }),
                          /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __framer__loop: animation,
                            __framer__loopEffectEnabled: true,
                            __framer__loopPauseOffscreen: false,
                            __framer__loopRepeatDelay: 1,
                            __framer__loopRepeatType: "loop",
                            __framer__loopTransition: transition2,
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 0.7,
                            className: "framer-11i07ya",
                            "data-framer-name": "Shiny frame",
                            layoutDependency: layoutDependency,
                            layoutId: "XnTBpzTXZ",
                            style: {
                              backgroundColor:
                                "var(--token-df0d70be-4f83-4b31-86f2-fe7fda12bad9, rgb(255, 255, 255))",
                              filter: "blur(0px)",
                              opacity: 0.7,
                              rotate: 28,
                              WebkitFilter: "blur(0px)",
                            },
                          }),
                        ],
                      }),
                  ],
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-pl9n0f",
                layoutDependency: layoutDependency,
                layoutId: "wJfWXYJUJ",
                children: /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-mdoc0f",
                  "data-framer-name": "Starter price",
                  layoutDependency: layoutDependency,
                  layoutId: "jILjmWxxU",
                  children: [
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-1pma0fr-container",
                          "data-code-component-plugin-id": "api",
                          isAuthoredByUser: true,
                          layoutDependency: layoutDependency,
                          layoutId: "jxy4uCb_s-container",
                          nodeId: "jxy4uCb_s",
                          rendersWithMotion: true,
                          scopeId: "trGKj0u8_",
                          children: /*#__PURE__*/ _jsx(SlotCounter, {
                            color:
                              "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072, rgb(0, 0, 0))",
                            decimals: 0,
                            digitGap: 1,
                            digitWidth: 0.63,
                            direction: "up",
                            duration: 1.3,
                            fadeEdges: true,
                            font: {
                              fontFamily:
                                '"PP Neue Montreal Medium", "PP Neue Montreal Medium Placeholder", sans-serif',
                              fontSize: "46px",
                              fontStyle: "normal",
                              fontWeight: 500,
                              letterSpacing: "-0.7px",
                              lineHeight: "1em",
                              textAlign: "left",
                            },
                            grouping: true,
                            height: "100%",
                            id: "jxy4uCb_s",
                            layoutId: "jxy4uCb_s",
                            prefix: "$",
                            replay: false,
                            rolls: 3,
                            stagger: 0.1,
                            staggerFrom: "left",
                            suffix: "",
                            trigger: "inView",
                            value: viOlM9VYn,
                            width: "100%",
                          }),
                        },
                      ),
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-kmegkv",
                          "data-styles-preset": "OsCWNv90r",
                          dir: "auto",
                          children: "/ month",
                        }),
                      }),
                      className: "framer-jr29dw",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "RkQXwPmyW",
                      text: HIb36ulNU,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  ],
                }),
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-kmegkv",
                    "data-styles-preset": "OsCWNv90r",
                    dir: "auto",
                    children:
                      "For individuals organizing and automating everyday work.",
                  }),
                }),
                className: "framer-7akcpq",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "xuYwwmfc5",
                text: Kjgt9_VjS,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1d6g2wu",
                "data-framer-name": "Starter divider",
                layoutDependency: layoutDependency,
                layoutId: "SwLMGRMlu",
                style: {
                  backgroundColor:
                    "var(--token-8144f193-de43-475d-87ea-e22ad062944c)",
                },
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-m10r77",
                    "data-styles-preset": "VMB1MMLPM",
                    dir: "auto",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-2e8179f9-642e-40f6-a729-9879c38a7c7c, rgba(0, 0, 0, 0.4)))",
                    },
                    children: "INCLUDES",
                  }),
                }),
                className: "framer-bv9hvx",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "YeAYts6g1",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-2e8179f9-642e-40f6-a729-9879c38a7c7c, rgba(0, 0, 0, 0.4))",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1vnli86",
                "data-framer-name": "Starter features",
                layoutDependency: layoutDependency,
                layoutId: "dHd1b1vfO",
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 25,
                    width: `calc(${componentViewport?.width || "100vw"} - 72px)`,
                    y:
                      (componentViewport?.y || 0) + 8 + 0 + 28 + 385.16 + 0 + 0,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1aui2ge-container",
                        layoutDependency: layoutDependency,
                        layoutId: "CfH_CH9_0-container",
                        nodeId: "CfH_CH9_0",
                        rendersWithMotion: true,
                        scopeId: "trGKj0u8_",
                        children: /*#__PURE__*/ _jsx(PricingList, {
                          height: "100%",
                          id: "CfH_CH9_0",
                          layoutId: "CfH_CH9_0",
                          N8q45UF5o: rvjiqNekA,
                          onN8q45UF5oChange: setrvjiqNekA,
                          style: { width: "100%" },
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 25,
                    width: `calc(${componentViewport?.width || "100vw"} - 72px)`,
                    y:
                      (componentViewport?.y || 0) +
                      8 +
                      0 +
                      28 +
                      385.16 +
                      0 +
                      39,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-sl9tse-container",
                        layoutDependency: layoutDependency,
                        layoutId: "CTvC_CoHz-container",
                        nodeId: "CTvC_CoHz",
                        rendersWithMotion: true,
                        scopeId: "trGKj0u8_",
                        children: /*#__PURE__*/ _jsx(PricingList, {
                          height: "100%",
                          id: "CTvC_CoHz",
                          layoutId: "CTvC_CoHz",
                          N8q45UF5o: RhGdP9vsz,
                          onN8q45UF5oChange: setRhGdP9vsz,
                          style: { width: "100%" },
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 25,
                    width: `calc(${componentViewport?.width || "100vw"} - 72px)`,
                    y:
                      (componentViewport?.y || 0) +
                      8 +
                      0 +
                      28 +
                      385.16 +
                      0 +
                      78,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1d2z3i-container",
                        layoutDependency: layoutDependency,
                        layoutId: "zu8nTJu6j-container",
                        nodeId: "zu8nTJu6j",
                        rendersWithMotion: true,
                        scopeId: "trGKj0u8_",
                        children: /*#__PURE__*/ _jsx(PricingList, {
                          height: "100%",
                          id: "zu8nTJu6j",
                          layoutId: "zu8nTJu6j",
                          N8q45UF5o: rLjb1sTpM,
                          onN8q45UF5oChange: setrLjb1sTpM,
                          style: { width: "100%" },
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 25,
                    width: `calc(${componentViewport?.width || "100vw"} - 72px)`,
                    y:
                      (componentViewport?.y || 0) +
                      8 +
                      0 +
                      28 +
                      385.16 +
                      0 +
                      117,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1bv0fjd-container",
                        layoutDependency: layoutDependency,
                        layoutId: "yqvsghxdw-container",
                        nodeId: "yqvsghxdw",
                        rendersWithMotion: true,
                        scopeId: "trGKj0u8_",
                        children: /*#__PURE__*/ _jsx(PricingList, {
                          height: "100%",
                          id: "yqvsghxdw",
                          layoutId: "yqvsghxdw",
                          N8q45UF5o: KGukpFXRd,
                          onN8q45UF5oChange: setKGukpFXRd,
                          style: { width: "100%" },
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 25,
                    width: `calc(${componentViewport?.width || "100vw"} - 72px)`,
                    y:
                      (componentViewport?.y || 0) +
                      8 +
                      0 +
                      28 +
                      385.16 +
                      0 +
                      156,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-10ig39u-container",
                        layoutDependency: layoutDependency,
                        layoutId: "Yj35SK7qS-container",
                        nodeId: "Yj35SK7qS",
                        rendersWithMotion: true,
                        scopeId: "trGKj0u8_",
                        children: /*#__PURE__*/ _jsx(PricingList, {
                          height: "100%",
                          id: "Yj35SK7qS",
                          layoutId: "Yj35SK7qS",
                          N8q45UF5o: EtXvqbnrf,
                          onN8q45UF5oChange: setEtXvqbnrf,
                          style: { width: "100%" },
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                ],
              }),
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 45,
                width: `calc(${componentViewport?.width || "100vw"} - 72px)`,
                y: (componentViewport?.y || 0) + 8 + 0 + 28 + 612.16,
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-14nxe93-container",
                  layoutDependency: layoutDependency,
                  layoutId: "RglcsgyyS-container",
                  nodeId: "RglcsgyyS",
                  rendersWithMotion: true,
                  scopeId: "trGKj0u8_",
                  children: /*#__PURE__*/ _jsx(Button, {
                    F05bztbU6: VNw9l7uWS,
                    height: "100%",
                    id: "RglcsgyyS",
                    layoutId: "RglcsgyyS",
                    oGE0W8Khx: Z7KoJzaTd,
                    onoGE0W8KhxChange: setZ7KoJzaTd,
                    style: { width: "100%" },
                    variant: matchVariant(B8WqQafkB),
                    VOL5lEKBp: true,
                    width: "100%",
                    yy2KWrRCF: ArrowRight,
                  }),
                }),
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  ".framer-ojBS5.framer-xldn7n, .framer-ojBS5 .framer-xldn7n { display: block; }",
  ".framer-ojBS5.framer-1q3xcpt { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 8px; position: relative; width: 496px; }",
  ".framer-ojBS5 .framer-1o3q9jv { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 22px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 28px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-ojBS5 .framer-r0fy2x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 0px; position: relative; width: 100%; }",
  ".framer-ojBS5 .framer-17c72qm { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 0px; position: relative; width: 1px; }",
  ".framer-ojBS5 .framer-1ittrum { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-ojBS5 .framer-1cq72z8, .framer-ojBS5 .framer-stuttq, .framer-ojBS5 .framer-jr29dw, .framer-ojBS5 .framer-bv9hvx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-ojBS5 .framer-ep8xlz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 4px 10px 4px 10px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-ojBS5 .framer-16anaen { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ojBS5 .framer-11i07ya { flex: none; height: 68px; left: -13px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: -47px; width: 9px; z-index: 1; }",
  ".framer-ojBS5 .framer-pl9n0f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-ojBS5 .framer-mdoc0f { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ojBS5 .framer-1pma0fr-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-ojBS5 .framer-7akcpq { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-ojBS5 .framer-1d6g2wu { flex: none; height: 1px; position: relative; width: 100%; }",
  ".framer-ojBS5 .framer-1vnli86 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; padding: 0px 0px 24px 0px; position: relative; width: 100%; z-index: 1; }",
  ".framer-ojBS5 .framer-1aui2ge-container, .framer-ojBS5 .framer-sl9tse-container, .framer-ojBS5 .framer-1d2z3i-container, .framer-ojBS5 .framer-1bv0fjd-container, .framer-ojBS5 .framer-10ig39u-container, .framer-ojBS5 .framer-14nxe93-container { flex: none; height: auto; position: relative; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  '.framer-ojBS5[data-border="true"]::after, .framer-ojBS5 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 572.5
 * @framerIntrinsicWidth 495.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"nXi9DWiJi":"popularTag","B8WqQafkB":"buttonVariant","Z7KoJzaTd":"label","HIb36ulNU":"period","viOlM9VYn":"value","rvjiqNekA":"feature1","RhGdP9vsz":"feature2","rLjb1sTpM":"feature3","KGukpFXRd":"feature4","EtXvqbnrf":"feature5","icLcyvEbo":"planName","Kjgt9_VjS":"planDescription","VNw9l7uWS":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramertrGKj0u8_ = withCSS(Component, css, "framer-ojBS5");
export default FramertrGKj0u8_;
FramertrGKj0u8_.displayName = "Pricing plan card";
FramertrGKj0u8_.defaultProps = { height: 572.5, width: 495.5 };
addPropertyControls(FramertrGKj0u8_, {
  nXi9DWiJi: {
    defaultValue: true,
    title: "Popular tag",
    type: ControlType.Boolean,
  },
  onnXi9DWiJiChange: { changes: "nXi9DWiJi", type: ControlType.ChangeHandler },
  B8WqQafkB: ButtonControls?.["variant"] && {
    ...ButtonControls["variant"],
    defaultValue: "jlYR3ckV6",
    description: undefined,
    hidden: undefined,
    optional: undefined,
    title: "Button variant",
  },
  onB8WqQafkBChange: { changes: "B8WqQafkB", type: ControlType.ChangeHandler },
  Z7KoJzaTd: {
    defaultValue: "Get started",
    displayTextArea: false,
    title: "Label",
    type: ControlType.String,
  },
  onZ7KoJzaTdChange: { changes: "Z7KoJzaTd", type: ControlType.ChangeHandler },
  HIb36ulNU: {
    defaultValue: "/ month",
    displayTextArea: false,
    title: "Period",
    type: ControlType.String,
  },
  onHIb36ulNUChange: { changes: "HIb36ulNU", type: ControlType.ChangeHandler },
  viOlM9VYn: {
    defaultValue: 99,
    displayStepper: true,
    step: 1,
    title: "Value",
    type: ControlType.Number,
  },
  onviOlM9VYnChange: { changes: "viOlM9VYn", type: ControlType.ChangeHandler },
  rvjiqNekA: {
    defaultValue: "Personal workspace",
    displayTextArea: false,
    title: "Feature 1",
    type: ControlType.String,
  },
  onrvjiqNekAChange: { changes: "rvjiqNekA", type: ControlType.ChangeHandler },
  RhGdP9vsz: {
    defaultValue: "Personal workspace",
    displayTextArea: false,
    title: "Feature 2",
    type: ControlType.String,
  },
  onRhGdP9vszChange: { changes: "RhGdP9vsz", type: ControlType.ChangeHandler },
  rLjb1sTpM: {
    defaultValue: "Personal workspace",
    displayTextArea: false,
    title: "Feature 3",
    type: ControlType.String,
  },
  onrLjb1sTpMChange: { changes: "rLjb1sTpM", type: ControlType.ChangeHandler },
  KGukpFXRd: {
    defaultValue: "Personal workspace",
    displayTextArea: false,
    title: "Feature 4",
    type: ControlType.String,
  },
  onKGukpFXRdChange: { changes: "KGukpFXRd", type: ControlType.ChangeHandler },
  EtXvqbnrf: {
    defaultValue: "Personal workspace",
    displayTextArea: false,
    title: "Feature 5",
    type: ControlType.String,
  },
  onEtXvqbnrfChange: { changes: "EtXvqbnrf", type: ControlType.ChangeHandler },
  icLcyvEbo: {
    defaultValue: "Starter",
    displayTextArea: false,
    title: "Plan name",
    type: ControlType.String,
  },
  onicLcyvEboChange: { changes: "icLcyvEbo", type: ControlType.ChangeHandler },
  Kjgt9_VjS: {
    defaultValue: "For individuals organizing and automating everyday work.",
    displayTextArea: false,
    title: "Plan description",
    type: ControlType.String,
  },
  onKjgt9_VjSChange: { changes: "Kjgt9_VjS", type: ControlType.ChangeHandler },
  VNw9l7uWS: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramertrGKj0u8_,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "PP Neue Montreal Medium",
          source: "custom",
          style: "normal",
          uiFamilyName: "PP Neue Montreal",
          url: "https://framerusercontent.com/assets/6uIfYl8bnz9kOy3KOuV7PxhFPhA.woff2",
          weight: "500",
        },
      ],
    },
    ...SlotCounterFonts,
    ...PricingListFonts,
    ...ButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
FramertrGKj0u8_.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(PricingList, {}, context),
      forwardLoader(Button, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramertrGKj0u8_",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerIntrinsicHeight: "572.5",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "495.5",
        framerVariables:
          '{"nXi9DWiJi":"popularTag","B8WqQafkB":"buttonVariant","Z7KoJzaTd":"label","HIb36ulNU":"period","viOlM9VYn":"value","rvjiqNekA":"feature1","RhGdP9vsz":"feature2","rLjb1sTpM":"feature3","KGukpFXRd":"feature4","EtXvqbnrf":"feature5","icLcyvEbo":"planName","Kjgt9_VjS":"planDescription","VNw9l7uWS":"link"}',
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./trGKj0u8_.map
