// Generated by Framer (560da95)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Instance,
  Link,
  RichText,
  runTasksWithYield,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ArrowRight from "./gXjG4ReaI.js";
import Menu from "./Vsaktx242.js";
import X from "./gpufTpA3b.js";
import * as sharedStyle1 from "./bY_LwQwga.js";
import * as sharedStyle from "./OsCWNv90r.js";
import Button from "./Jh9jZPCX6.js";
const ButtonFonts = getFonts(Button);
const cycleOrder = ["SSKhviVYR", "VQTwPyCP_", "bLrSKPEk8"];
const serializationHash = "framer-dHlUL";
const variantClassNames = {
  bLrSKPEk8: "framer-v-33a66s",
  SSKhviVYR: "framer-v-1h93pqc",
  VQTwPyCP_: "framer-v-1xwh6e5",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  delay: 0,
  duration: 0.35,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const transition3 = { bounce: 0.25, delay: 0, duration: 0.35, type: "spring" };
const transition4 = { bounce: 0.2, delay: 0, duration: 0.3, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  "Phone Closed": "VQTwPyCP_",
  "Phone Open": "bLrSKPEk8",
  Desktop: "SSKhviVYR",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "SSKhviVYR",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "SSKhviVYR",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["VQTwPyCP_", "bLrSKPEk8"].includes(baseVariant)) return true;
    return false;
  };
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1fi1fj3 = activeVariantCallback(async (...args) => {
    setVariant("bLrSKPEk8");
  });
  const onTapm04s4f = activeVariantCallback(async (...args) => {
    setVariant("VQTwPyCP_");
  });
  const isDisplayed1 = () => {
    if (baseVariant === "VQTwPyCP_") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          {
            bLrSKPEk8: { value: transition3 },
            VQTwPyCP_: { value: transition2 },
          },
          baseVariant,
          gestureVariant,
        ),
        children: /*#__PURE__*/ _jsxs(motion.nav, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1h93pqc",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "SSKhviVYR",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color":
              "var(--token-8144f193-de43-475d-87ea-e22ad062944c)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor:
              "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b)",
            borderBottomLeftRadius: 1e3,
            borderBottomRightRadius: 1e3,
            borderTopLeftRadius: 1e3,
            borderTopRightRadius: 1e3,
            ...style,
          },
          variants: {
            bLrSKPEk8: {
              borderBottomLeftRadius: 24,
              borderBottomRightRadius: 24,
              borderTopLeftRadius: 24,
              borderTopRightRadius: 24,
            },
            VQTwPyCP_: {
              borderBottomLeftRadius: 24,
              borderBottomRightRadius: 24,
              borderTopLeftRadius: 24,
              borderTopRightRadius: 24,
            },
          },
          ...addPropertyOverrides(
            {
              bLrSKPEk8: { "data-framer-name": "Phone Open" },
              VQTwPyCP_: { "data-framer-name": "Phone Closed" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-k4j80w",
              "data-framer-name": "Logo container",
              layoutDependency: layoutDependency,
              layoutId: "v1CjvD_6m",
              children: [
                /*#__PURE__*/ _jsx(Link, {
                  href: { hash: ":B5_U9VCRp", webPageId: "augiA20Il" },
                  motionChild: true,
                  nodeId: "G5HJH2HWZ",
                  openInNewTab: false,
                  scopeId: "UXHe4J1PZ",
                  children: /*#__PURE__*/ _jsx(Image1, {
                    as: "a",
                    background: {
                      alt: "",
                      fit: "fit",
                      intrinsicHeight: 3599,
                      intrinsicWidth: 4724,
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) +
                          (6 +
                            ((componentViewport?.height || 54) -
                              12 -
                              ((componentViewport?.height || 54) - 12) * 1) /
                              2) +
                          (8 +
                            (((componentViewport?.height || 54) - 12) * 1 -
                              16 -
                              (((componentViewport?.height || 54) - 12) * 1 -
                                16) *
                                1) /
                              2),
                      ),
                      pixelHeight: 3599,
                      pixelWidth: 4724,
                      positionX: "center",
                      positionY: "center",
                      sizes: `calc(${(((componentViewport?.height || 54) - 12) * 1 - 16) * 1} * 5.1184)`,
                      src: "https://framerusercontent.com/images/5rnS6ZCipvO1sGwgHOoGCHbeQ.png?width=4724&height=3599",
                    },
                    className: "framer-1u13xeq framer-156rhz7",
                    "data-framer-name": "Company logo placeholder",
                    layoutDependency: layoutDependency,
                    layoutId: "G5HJH2HWZ",
                    style: { originX: 0.9, scale: 1.6 },
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          background: {
                            alt: "",
                            fit: "fit",
                            intrinsicHeight: 3599,
                            intrinsicWidth: 4724,
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) + 8 + 0 + 0,
                            ),
                            pixelHeight: 3599,
                            pixelWidth: 4724,
                            positionX: "center",
                            positionY: "center",
                            sizes: "125px",
                            src: "https://framerusercontent.com/images/5rnS6ZCipvO1sGwgHOoGCHbeQ.png?width=4724&height=3599",
                          },
                        },
                        VQTwPyCP_: {
                          background: {
                            alt: "",
                            fit: "fit",
                            intrinsicHeight: 3599,
                            intrinsicWidth: 4724,
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) + 8 + 0 + 0,
                            ),
                            pixelHeight: 3599,
                            pixelWidth: 4724,
                            positionX: "center",
                            positionY: "center",
                            sizes: "125px",
                            src: "https://framerusercontent.com/images/5rnS6ZCipvO1sGwgHOoGCHbeQ.png?width=4724&height=3599",
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                }),
                isDisplayed() &&
                  /*#__PURE__*/ _jsx(Transition, {
                    value: transition4,
                    children: /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1h8j2x1",
                      "data-border": true,
                      "data-framer-name": "Mobile menu trigger",
                      layoutDependency: layoutDependency,
                      layoutId: "OIdQOqhKN",
                      style: {
                        "--border-bottom-width": "1px",
                        "--border-color":
                          "var(--token-8144f193-de43-475d-87ea-e22ad062944c)",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor:
                          "var(--token-4b2e1e47-a7ec-4fea-a0ce-eadd74c77d3b)",
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                      },
                      ...addPropertyOverrides(
                        {
                          bLrSKPEk8: {
                            "data-highlight": true,
                            onTap: onTapm04s4f,
                          },
                          VQTwPyCP_: {
                            "data-highlight": true,
                            onTap: onTap1fi1fj3,
                          },
                        },
                        baseVariant,
                        gestureVariant,
                      ),
                      children: /*#__PURE__*/ _jsx(Instance, {
                        animated: true,
                        className: "framer-ejcmu9",
                        Component: Menu,
                        layoutDependency: layoutDependency,
                        layoutId: "zuzY2kc3M",
                        style: {
                          "--1m973uw":
                            "var(--token-7ce17e0b-526a-4831-8d21-f7773fb57072)",
                          "--js9iwy": 2,
                        },
                        ...addPropertyOverrides(
                          { bLrSKPEk8: { Component: X } },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    }),
                  }),
              ],
            }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-7po77i",
                "data-framer-name": "Navigation links",
                layoutDependency: layoutDependency,
                layoutId: "BnEu9Isys",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-kmegkv",
                        "data-styles-preset": "OsCWNv90r",
                        dir: "auto",
                        children: /*#__PURE__*/ _jsx(Link, {
                          href: { hash: ":DXn5Hibuv", webPageId: "augiA20Il" },
                          motionChild: true,
                          nodeId: "jp2UhyVj5",
                          openInNewTab: false,
                          relValues: [],
                          scopeId: "UXHe4J1PZ",
                          smoothScroll: true,
                          children: /*#__PURE__*/ _jsx(motion.a, {
                            className: "framer-styles-preset-75bc7e",
                            "data-styles-preset": "bY_LwQwga",
                            children: "Solution",
                          }),
                        }),
                      }),
                    }),
                    className: "framer-h0t69z",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "jp2UhyVj5",
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          "data-highlight": true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              style: { "--framer-text-alignment": "start" },
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: {
                                  hash: ":DXn5Hibuv",
                                  webPageId: "augiA20Il",
                                },
                                motionChild: true,
                                nodeId: "jp2UhyVj5",
                                openInNewTab: false,
                                relValues: [],
                                scopeId: "UXHe4J1PZ",
                                smoothScroll: true,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-75bc7e",
                                  "data-styles-preset": "bY_LwQwga",
                                  children: "Solution",
                                }),
                              }),
                            }),
                          }),
                          onTap: onTapm04s4f,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-kmegkv",
                        "data-styles-preset": "OsCWNv90r",
                        dir: "auto",
                        children: /*#__PURE__*/ _jsx(Link, {
                          href: { hash: ":W_2F8FmqT", webPageId: "augiA20Il" },
                          motionChild: true,
                          nodeId: "OGbVj23E8",
                          openInNewTab: false,
                          relValues: [],
                          scopeId: "UXHe4J1PZ",
                          smoothScroll: true,
                          children: /*#__PURE__*/ _jsx(motion.a, {
                            className: "framer-styles-preset-75bc7e",
                            "data-styles-preset": "bY_LwQwga",
                            children: "Platform",
                          }),
                        }),
                      }),
                    }),
                    className: "framer-1a0cz71",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "OGbVj23E8",
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          "data-highlight": true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              style: { "--framer-text-alignment": "start" },
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: {
                                  hash: ":W_2F8FmqT",
                                  webPageId: "augiA20Il",
                                },
                                motionChild: true,
                                nodeId: "OGbVj23E8",
                                openInNewTab: false,
                                relValues: [],
                                scopeId: "UXHe4J1PZ",
                                smoothScroll: true,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-75bc7e",
                                  "data-styles-preset": "bY_LwQwga",
                                  children: "Platform",
                                }),
                              }),
                            }),
                          }),
                          onTap: onTapm04s4f,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-kmegkv",
                        "data-styles-preset": "OsCWNv90r",
                        dir: "auto",
                        children: /*#__PURE__*/ _jsx(Link, {
                          href: { hash: ":UMje28XpX", webPageId: "augiA20Il" },
                          motionChild: true,
                          nodeId: "dTREWZcfg",
                          openInNewTab: false,
                          relValues: [],
                          scopeId: "UXHe4J1PZ",
                          smoothScroll: true,
                          children: /*#__PURE__*/ _jsx(motion.a, {
                            className: "framer-styles-preset-75bc7e",
                            "data-styles-preset": "bY_LwQwga",
                            children: "Integrations",
                          }),
                        }),
                      }),
                    }),
                    className: "framer-16agxcd",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "dTREWZcfg",
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          "data-highlight": true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              style: { "--framer-text-alignment": "start" },
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: {
                                  hash: ":UMje28XpX",
                                  webPageId: "augiA20Il",
                                },
                                motionChild: true,
                                nodeId: "dTREWZcfg",
                                openInNewTab: false,
                                relValues: [],
                                scopeId: "UXHe4J1PZ",
                                smoothScroll: true,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-75bc7e",
                                  "data-styles-preset": "bY_LwQwga",
                                  children: "Integrations",
                                }),
                              }),
                            }),
                          }),
                          onTap: onTapm04s4f,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-kmegkv",
                        "data-styles-preset": "OsCWNv90r",
                        dir: "auto",
                        children: /*#__PURE__*/ _jsx(Link, {
                          href: { hash: ":WYSe0v1Nz", webPageId: "augiA20Il" },
                          motionChild: true,
                          nodeId: "vSuBdhCSN",
                          openInNewTab: false,
                          relValues: [],
                          scopeId: "UXHe4J1PZ",
                          smoothScroll: true,
                          children: /*#__PURE__*/ _jsx(motion.a, {
                            className: "framer-styles-preset-75bc7e",
                            "data-styles-preset": "bY_LwQwga",
                            children: "Security",
                          }),
                        }),
                      }),
                    }),
                    className: "framer-19masf1",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "vSuBdhCSN",
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          "data-highlight": true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-kmegkv",
                              "data-styles-preset": "OsCWNv90r",
                              dir: "auto",
                              style: { "--framer-text-alignment": "start" },
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: {
                                  hash: ":WYSe0v1Nz",
                                  webPageId: "augiA20Il",
                                },
                                motionChild: true,
                                nodeId: "vSuBdhCSN",
                                openInNewTab: false,
                                relValues: [],
                                scopeId: "UXHe4J1PZ",
                                smoothScroll: true,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-75bc7e",
                                  "data-styles-preset": "bY_LwQwga",
                                  children: "Security",
                                }),
                              }),
                            }),
                          }),
                          onTap: onTapm04s4f,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                ],
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1ffu7py",
                "data-framer-name": "Navigation actions",
                layoutDependency: layoutDependency,
                layoutId: "LvBDopLF8",
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 45,
                    y:
                      (componentViewport?.y || 0) +
                      (6 + ((componentViewport?.height || 54) - 12 - 49) / 2) +
                      2,
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          y: (componentViewport?.y || 0) + 8 + 664 + 8,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1slxfrz-container",
                        layoutDependency: layoutDependency,
                        layoutId: "Sf14Jn2AC-container",
                        nodeId: "Sf14Jn2AC",
                        rendersWithMotion: true,
                        scopeId: "UXHe4J1PZ",
                        children: /*#__PURE__*/ _jsx(Button, {
                          F05bztbU6: "https://framer.link/ridham43",
                          height: "100%",
                          id: "Sf14Jn2AC",
                          layoutId: "Sf14Jn2AC",
                          oGE0W8Khx: "Explore Solutions ",
                          variant: matchVariant("L4yW9kxuA"),
                          VOL5lEKBp: false,
                          width: "100%",
                          yy2KWrRCF: ArrowRight,
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 45,
                    y:
                      (componentViewport?.y || 0) +
                      (6 + ((componentViewport?.height || 54) - 12 - 49) / 2) +
                      2,
                    ...addPropertyOverrides(
                      {
                        bLrSKPEk8: {
                          y: (componentViewport?.y || 0) + 8 + 664 + 8,
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1rxy5s0-container",
                        layoutDependency: layoutDependency,
                        layoutId: "OWZzdEOKx-container",
                        nodeId: "OWZzdEOKx",
                        rendersWithMotion: true,
                        scopeId: "UXHe4J1PZ",
                        children: /*#__PURE__*/ _jsx(Button, {
                          F05bztbU6: "https://framer.link/nMYvgrH",
                          height: "100%",
                          id: "OWZzdEOKx",
                          layoutId: "OWZzdEOKx",
                          oGE0W8Khx: "Request a demo",
                          variant: matchVariant("YnCyd7g0P"),
                          VOL5lEKBp: false,
                          width: "100%",
                          yy2KWrRCF: ArrowRight,
                        }),
                      },
                    ),
                  }),
                ],
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-dHlUL.framer-156rhz7, .framer-dHlUL .framer-156rhz7 { display: block; }",
  ".framer-dHlUL.framer-1h93pqc { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 6px 8px 6px 8px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-dHlUL .framer-k4j80w { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: flex-start; overflow: visible; padding: 8px 0px 8px 4px; position: relative; width: 1px; }",
  ".framer-dHlUL .framer-1u13xeq { align-content: center; align-items: center; aspect-ratio: 5.118421052631579 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; padding: 12px 18px 12px 18px; position: relative; text-decoration: none; width: auto; }",
  ".framer-dHlUL .framer-1h8j2x1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 44px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 44px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-dHlUL .framer-ejcmu9 { flex: none; height: auto; position: relative; width: 20px; }",
  ".framer-dHlUL .framer-7po77i { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 1px; }",
  ".framer-dHlUL .framer-h0t69z, .framer-dHlUL .framer-1a0cz71, .framer-dHlUL .framer-16agxcd, .framer-dHlUL .framer-19masf1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-dHlUL .framer-1ffu7py { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-end; padding: 2px 0px 2px 0px; position: relative; width: 1px; }",
  ".framer-dHlUL .framer-1slxfrz-container, .framer-dHlUL .framer-1rxy5s0-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-dHlUL.framer-v-1xwh6e5.framer-1h93pqc { flex-direction: column; gap: 4px; justify-content: flex-start; padding: 8px; width: 390px; }",
  ".framer-dHlUL.framer-v-1xwh6e5 .framer-k4j80w, .framer-dHlUL.framer-v-33a66s .framer-k4j80w { align-self: unset; flex: none; gap: unset; height: min-content; justify-content: space-between; padding: 0px 0px 0px 8px; width: 100%; }",
  ".framer-dHlUL.framer-v-1xwh6e5 .framer-1u13xeq, .framer-dHlUL.framer-v-33a66s .framer-1u13xeq { align-self: stretch; aspect-ratio: unset; cursor: default; height: auto; padding: 10px 16px 10px 16px; width: 125px; }",
  ".framer-dHlUL.framer-v-33a66s.framer-1h93pqc { flex-direction: column; gap: 4px; justify-content: flex-start; min-height: calc(var(--framer-viewport-height, 100vh) * 1); padding: 8px; width: 390px; }",
  ".framer-dHlUL.framer-v-33a66s .framer-7po77i { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; gap: 20px; justify-content: flex-start; min-height: 100px; padding: 20px 16px 20px 16px; width: 100%; }",
  ".framer-dHlUL.framer-v-33a66s .framer-h0t69z, .framer-dHlUL.framer-v-33a66s .framer-1a0cz71, .framer-dHlUL.framer-v-33a66s .framer-16agxcd, .framer-dHlUL.framer-v-33a66s .framer-19masf1 { --framer-custom-cursors: pointer; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-dHlUL.framer-v-33a66s .framer-1ffu7py { flex: none; gap: 8px; justify-content: flex-start; padding: 8px; width: 100%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-dHlUL[data-border="true"]::after, .framer-dHlUL [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 54
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VQTwPyCP_":{"layout":["fixed","auto"]},"bLrSKPEk8":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerUXHe4J1PZ = withCSS(Component, css, "framer-dHlUL");
export default FramerUXHe4J1PZ;
FramerUXHe4J1PZ.displayName = "Navigation bar";
FramerUXHe4J1PZ.defaultProps = { height: 54, width: 1200 };
addPropertyControls(FramerUXHe4J1PZ, {
  variant: {
    options: ["SSKhviVYR", "VQTwPyCP_", "bLrSKPEk8"],
    optionTitles: ["Desktop", "Phone Closed", "Phone Open"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerUXHe4J1PZ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true },
);
FramerUXHe4J1PZ.loader = {
  load: (props, context) => {
    return runTasksWithYield(
      [() => forwardLoader(Button, {}, context)],
      context,
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerUXHe4J1PZ",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "54",
        framerContractVersion: "1",
        framerIntrinsicWidth: "1200",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VQTwPyCP_":{"layout":["fixed","auto"]},"bLrSKPEk8":{"layout":["fixed","auto"],"constraints":[null,null,"100vh",null]}}}',
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./UXHe4J1PZ.map
