// Generated by Framer (e1541bb)
import { fontStore } from "framer";
fontStore.loadFonts([
  "GF;Geist-500",
  "GF;Geist-700",
  "GF;Geist-700italic",
  "GF;Geist-500italic",
]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "Geist",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v5/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
        weight: "500",
      },
      {
        cssFamilyName: "Geist",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v5/gyBhhwUxId8gMGYQMKR3pzfaWI_Re-Q4mJPby1QNtA.woff2",
        weight: "700",
      },
      {
        cssFamilyName: "Geist",
        openType: true,
        source: "google",
        style: "italic",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v5/gyBjhwUxId8gMEwZAluvzlxA9ojEVKA32Zna6VEdtKCL.woff2",
        weight: "700",
      },
      {
        cssFamilyName: "Geist",
        openType: true,
        source: "google",
        style: "italic",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v5/gyBjhwUxId8gMEwZAluvzlxA9ojEVKDi3pna6VEdtKCL.woff2",
        weight: "500",
      },
    ],
  },
];
export const css = [
  '.framer-eTby8 .framer-styles-preset-m10r77:not(.rich-text-wrapper), .framer-eTby8 .framer-styles-preset-m10r77.rich-text-wrapper p { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold-italic: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-italic: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: \'blwf\' on, \'cv03\' on, \'cv04\' on, \'cv09\' on, \'cv11\' on; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0px; --framer-line-height: 1.35em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-faa83f4b-eb5a-4111-a586-ff3633f4da58, rgba(0, 0, 0, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-eTby8 .framer-styles-preset-m10r77:not(.rich-text-wrapper), .framer-eTby8 .framer-styles-preset-m10r77.rich-text-wrapper p { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold-italic: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-italic: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: \'blwf\' on, \'cv03\' on, \'cv04\' on, \'cv09\' on, \'cv11\' on; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.35em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-faa83f4b-eb5a-4111-a586-ff3633f4da58, rgba(0, 0, 0, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-eTby8 .framer-styles-preset-m10r77:not(.rich-text-wrapper), .framer-eTby8 .framer-styles-preset-m10r77.rich-text-wrapper p { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold-italic: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-italic: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: \'blwf\' on, \'cv03\' on, \'cv04\' on, \'cv09\' on, \'cv11\' on; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.35em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-faa83f4b-eb5a-4111-a586-ff3633f4da58, rgba(0, 0, 0, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
export const className = "framer-eTby8";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
