// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask =
  'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 18 8.5 C 18.003 9.82 17.695 11.122 17.1 12.3 C 15.661 15.179 12.719 16.999 9.5 17 C 8.18 17.003 6.878 16.695 5.7 16.1 L 0 18 L 1.9 12.3 C 1.305 11.122 0.997 9.82 1 8.5 C 1.001 5.281 2.821 2.339 5.7 0.9 C 6.878 0.305 8.18 -0.003 9.5 0 L 10 0 C 14.316 0.238 17.762 3.684 18 8 Z" fill="transparent" height="18.00002848810215px" id="k0tMiR1Da" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(3 3)" width="18.000028488102146px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ height, id, stroke, width, ...props }) => {
  return { ...props, UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)" };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
    getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-ww8no", className),
    layoutId: layoutId,
    ref: ref,
    style: { "--43q7um": UO5clYVeQ, ...style },
  });
});
const css = [
  `.framer-ww8no { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"UO5clYVeQ":"stroke"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Message Circle","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-ww8no");
Icon.displayName = "Message Circle";
export default Icon;
addPropertyControls(Icon, {
  UO5clYVeQ: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Stroke",
    type: ControlType.Color,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerDisableUnlink: "true",
        framerIntrinsicWidth: "24",
        framerVector:
          '{"name":"Message Circle","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}',
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerContractVersion: "1",
        framerIntrinsicHeight: "24",
        framerVariables: '{"UO5clYVeQ":"stroke"}',
        framerSupportedLayoutWidth: "any-prefer-fixed",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
